//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4961
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sce.Sled.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sce.Sled.Resources.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify Condition.
        /// </summary>
        internal static string BreakpointWindowCondition {
            get {
                return ResourceManager.GetString("BreakpointWindowCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add / remove a condition to the breakpoint.
        /// </summary>
        internal static string BreakpointWindowConditionComment {
            get {
                return ResourceManager.GetString("BreakpointWindowConditionComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable Condition.
        /// </summary>
        internal static string BreakpointWindowConditionDisable {
            get {
                return ResourceManager.GetString("BreakpointWindowConditionDisable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable the breakpoint&apos;s condition.
        /// </summary>
        internal static string BreakpointWindowConditionDisableComment {
            get {
                return ResourceManager.GetString("BreakpointWindowConditionDisableComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Condition.
        /// </summary>
        internal static string BreakpointWindowConditionEnable {
            get {
                return ResourceManager.GetString("BreakpointWindowConditionEnable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable the breakpoint&apos;s condition.
        /// </summary>
        internal static string BreakpointWindowConditionEnableComment {
            get {
                return ResourceManager.GetString("BreakpointWindowConditionEnableComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable.
        /// </summary>
        internal static string BreakpointWindowDisable {
            get {
                return ResourceManager.GetString("BreakpointWindowDisable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disables the breakpoint so it will not be hit.
        /// </summary>
        internal static string BreakpointWindowDisableComment {
            get {
                return ResourceManager.GetString("BreakpointWindowDisableComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable.
        /// </summary>
        internal static string BreakpointWindowEnable {
            get {
                return ResourceManager.GetString("BreakpointWindowEnable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enables the breakpoint so it will be hit.
        /// </summary>
        internal static string BreakpointWindowEnableComment {
            get {
                return ResourceManager.GetString("BreakpointWindowEnableComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Breakpoints.
        /// </summary>
        internal static string BreakpointWindowName {
            get {
                return ResourceManager.GetString("BreakpointWindowName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        internal static string BreakpointWindowRemove {
            get {
                return ResourceManager.GetString("BreakpointWindowRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove All Selected.
        /// </summary>
        internal static string BreakpointWindowRemoveAll {
            get {
                return ResourceManager.GetString("BreakpointWindowRemoveAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove all of the selected breakpoints.
        /// </summary>
        internal static string BreakpointWindowRemoveAllComment {
            get {
                return ResourceManager.GetString("BreakpointWindowRemoveAllComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removes the breakpoint.
        /// </summary>
        internal static string BreakpointWindowRemoveComment {
            get {
                return ResourceManager.GetString("BreakpointWindowRemoveComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string SledAdd {
            get {
                return ResourceManager.GetString("SledAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Add File.
        /// </summary>
        internal static string SledAddFile {
            get {
                return ResourceManager.GetString("SledAddFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File was unable to open - perhaps the asset directory is wrong?.
        /// </summary>
        internal static string SledAssetDirectoryErrorFileUnableToOpen {
            get {
                return ResourceManager.GetString("SledAssetDirectoryErrorFileUnableToOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like SLED to attempt to change the file permissions and remove the read only flag?.
        /// </summary>
        internal static string SledAttemptChangeFilePermissions {
            get {
                return ResourceManager.GetString("SledAttemptChangeFilePermissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Breakpoint Condition Error.
        /// </summary>
        internal static string SledBreakpointConditionError {
            get {
                return ResourceManager.GetString("SledBreakpointConditionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The breakpoint condition cannot be empty when &quot;Condition&quot; is checked..
        /// </summary>
        internal static string SledBreakpointConditionErrorNoCondition {
            get {
                return ResourceManager.GetString("SledBreakpointConditionErrorNoCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrapped condition to be sent to target:%s0%s0%s1%s0%s0Syntax Error:%s0    %s2.
        /// </summary>
        internal static string SledBreakpointConditionErrorVarArg {
            get {
                return ResourceManager.GetString("SledBreakpointConditionErrorVarArg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Syntax Error.
        /// </summary>
        internal static string SledBreakpointConditionSyntaxError {
            get {
                return ResourceManager.GetString("SledBreakpointConditionSyntaxError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Breakpoint] Exception removing breakpoint on line %s0 from file %s1: %s2.
        /// </summary>
        internal static string SledBreakpointErrorRemoving {
            get {
                return ResourceManager.GetString("SledBreakpointErrorRemoving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Breakpoint.
        /// </summary>
        internal static string SledBreakpointMenuBreakpointAdd {
            get {
                return ResourceManager.GetString("SledBreakpointMenuBreakpointAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adds a breakpoint to the current line.
        /// </summary>
        internal static string SledBreakpointMenuBreakpointAddComment {
            get {
                return ResourceManager.GetString("SledBreakpointMenuBreakpointAddComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Condition.
        /// </summary>
        internal static string SledBreakpointMenuBreakpointCondition {
            get {
                return ResourceManager.GetString("SledBreakpointMenuBreakpointCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add / remove a condition to the breakpoint.
        /// </summary>
        internal static string SledBreakpointMenuBreakpointConditionComment {
            get {
                return ResourceManager.GetString("SledBreakpointMenuBreakpointConditionComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable Breakpoint.
        /// </summary>
        internal static string SledBreakpointMenuBreakpointDisable {
            get {
                return ResourceManager.GetString("SledBreakpointMenuBreakpointDisable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disables the breakpoint so it will not be hit.
        /// </summary>
        internal static string SledBreakpointMenuBreakpointDisableComment {
            get {
                return ResourceManager.GetString("SledBreakpointMenuBreakpointDisableComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Breakpoint.
        /// </summary>
        internal static string SledBreakpointMenuBreakpointEnable {
            get {
                return ResourceManager.GetString("SledBreakpointMenuBreakpointEnable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enables the breakpoint so it will be hit.
        /// </summary>
        internal static string SledBreakpointMenuBreakpointEnableComment {
            get {
                return ResourceManager.GetString("SledBreakpointMenuBreakpointEnableComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Breakpoint.
        /// </summary>
        internal static string SledBreakpointMenuBreakpointRemove {
            get {
                return ResourceManager.GetString("SledBreakpointMenuBreakpointRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove All Breakpoints.
        /// </summary>
        internal static string SledBreakpointMenuBreakpointRemoveAll {
            get {
                return ResourceManager.GetString("SledBreakpointMenuBreakpointRemoveAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove all breakpoints from the file.
        /// </summary>
        internal static string SledBreakpointMenuBreakpointRemoveAllComment {
            get {
                return ResourceManager.GetString("SledBreakpointMenuBreakpointRemoveAllComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removes the breakpoint on the current line.
        /// </summary>
        internal static string SledBreakpointMenuBreakpointRemoveComment {
            get {
                return ResourceManager.GetString("SledBreakpointMenuBreakpointRemoveComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot make changes at this time!.
        /// </summary>
        internal static string SledCannotMakeChanges {
            get {
                return ResourceManager.GetString("SledCannotMakeChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Close.
        /// </summary>
        internal static string SledClose {
            get {
                return ResourceManager.GetString("SledClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close an open file.
        /// </summary>
        internal static string SledCommandFileCloseComment {
            get {
                return ResourceManager.GetString("SledCommandFileCloseComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new text file.
        /// </summary>
        internal static string SledCommandFileNewTextComment {
            get {
                return ResourceManager.GetString("SledCommandFileNewTextComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open an existing file.
        /// </summary>
        internal static string SledCommandFileOpenComment {
            get {
                return ResourceManager.GetString("SledCommandFileOpenComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Find and Replace.
        /// </summary>
        internal static string SledCommandFindReplace {
            get {
                return ResourceManager.GetString("SledCommandFindReplace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F&amp;ind in Files.
        /// </summary>
        internal static string SledCommandFindReplaceFindInFiles {
            get {
                return ResourceManager.GetString("SledCommandFindReplaceFindInFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find and replace find in files.
        /// </summary>
        internal static string SledCommandFindReplaceFindInFilesComment {
            get {
                return ResourceManager.GetString("SledCommandFindReplaceFindInFilesComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find Next Instance of Selected Text Up Without GUI.
        /// </summary>
        internal static string SledCommandFindReplaceFindNextInstanceOfSelectedTextUpWithoutGUI {
            get {
                return ResourceManager.GetString("SledCommandFindReplaceFindNextInstanceOfSelectedTextUpWithoutGUI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find the next instance of the currently selected text searching up without using the GUI.
        /// </summary>
        internal static string SledCommandFindReplaceFindNextInstanceOfSelectedTextUpWithoutGUIComment {
            get {
                return ResourceManager.GetString("SledCommandFindReplaceFindNextInstanceOfSelectedTextUpWithoutGUIComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find Next Instance of Selected Text Without GUI.
        /// </summary>
        internal static string SledCommandFindReplaceFindNextInstanceOfSelectedTextWithoutGUI {
            get {
                return ResourceManager.GetString("SledCommandFindReplaceFindNextInstanceOfSelectedTextWithoutGUI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find the next instance of the currently selected text without using the GUI.
        /// </summary>
        internal static string SledCommandFindReplaceFindNextInstanceOfSelectedTextWithoutGUIComment {
            get {
                return ResourceManager.GetString("SledCommandFindReplaceFindNextInstanceOfSelectedTextWithoutGUIComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quick &amp;Find.
        /// </summary>
        internal static string SledCommandFindReplaceQuickFind {
            get {
                return ResourceManager.GetString("SledCommandFindReplaceQuickFind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find and replace quick find.
        /// </summary>
        internal static string SledCommandFindReplaceQuickFindComment {
            get {
                return ResourceManager.GetString("SledCommandFindReplaceQuickFindComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quick &amp;Replace.
        /// </summary>
        internal static string SledCommandFindReplaceQuickReplace {
            get {
                return ResourceManager.GetString("SledCommandFindReplaceQuickReplace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find and replace quick replace.
        /// </summary>
        internal static string SledCommandFindReplaceQuickReplaceComment {
            get {
                return ResourceManager.GetString("SledCommandFindReplaceQuickReplaceComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeat Last Search Up Without Using GUI.
        /// </summary>
        internal static string SledCommandFindReplaceRepeatLastSearchUpWithoutGui {
            get {
                return ResourceManager.GetString("SledCommandFindReplaceRepeatLastSearchUpWithoutGui", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeat the last performed search searching up and without using the GUI.
        /// </summary>
        internal static string SledCommandFindReplaceRepeatLastSearchUpWithoutGuiComment {
            get {
                return ResourceManager.GetString("SledCommandFindReplaceRepeatLastSearchUpWithoutGuiComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeat Last Search Without Using GUI.
        /// </summary>
        internal static string SledCommandFindReplaceRepeatLastSearchWithoutGui {
            get {
                return ResourceManager.GetString("SledCommandFindReplaceRepeatLastSearchWithoutGui", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeat the last performed search but without using the GUI.
        /// </summary>
        internal static string SledCommandFindReplaceRepeatLastSearchWithoutGuiComment {
            get {
                return ResourceManager.GetString("SledCommandFindReplaceRepeatLastSearchWithoutGuiComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace in File&amp;s.
        /// </summary>
        internal static string SledCommandFindReplaceReplaceInFiles {
            get {
                return ResourceManager.GetString("SledCommandFindReplaceReplaceInFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find and replace replace in files.
        /// </summary>
        internal static string SledCommandFindReplaceReplaceInFilesComment {
            get {
                return ResourceManager.GetString("SledCommandFindReplaceReplaceInFilesComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Go to....
        /// </summary>
        internal static string SledCommandGoto {
            get {
                return ResourceManager.GetString("SledCommandGoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to line.
        /// </summary>
        internal static string SledCommandGotoComment {
            get {
                return ResourceManager.GetString("SledCommandGotoComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected.
        /// </summary>
        internal static string SledConnected {
            get {
                return ResourceManager.GetString("SledConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Connect.
        /// </summary>
        internal static string SledDebugMenuConnect {
            get {
                return ResourceManager.GetString("SledDebugMenuConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect to a target.
        /// </summary>
        internal static string SledDebugMenuConnectComment {
            get {
                return ResourceManager.GetString("SledDebugMenuConnectComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Disconnect.
        /// </summary>
        internal static string SledDebugMenuDisconnect {
            get {
                return ResourceManager.GetString("SledDebugMenuDisconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnect from a target.
        /// </summary>
        internal static string SledDebugMenuDisconnectComment {
            get {
                return ResourceManager.GetString("SledDebugMenuDisconnectComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heartbeat.
        /// </summary>
        internal static string SledDebugMenuHeartbeat {
            get {
                return ResourceManager.GetString("SledDebugMenuHeartbeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle the heartbeat.
        /// </summary>
        internal static string SledDebugMenuHeartbeatComment {
            get {
                return ResourceManager.GetString("SledDebugMenuHeartbeatComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCMP Logging.
        /// </summary>
        internal static string SledDebugMenuScmpProtocolLogging {
            get {
                return ResourceManager.GetString("SledDebugMenuScmpProtocolLogging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle SCMP Logging.
        /// </summary>
        internal static string SledDebugMenuScmpProtocolLoggingComment {
            get {
                return ResourceManager.GetString("SledDebugMenuScmpProtocolLoggingComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send SCMP Mark.
        /// </summary>
        internal static string SledDebugMenuScmpProtocolMark {
            get {
                return ResourceManager.GetString("SledDebugMenuScmpProtocolMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send SCMP mark.
        /// </summary>
        internal static string SledDebugMenuScmpProtocolMarkComment {
            get {
                return ResourceManager.GetString("SledDebugMenuScmpProtocolMarkComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Start.
        /// </summary>
        internal static string SledDebugMenuStart {
            get {
                return ResourceManager.GetString("SledDebugMenuStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start debugging.
        /// </summary>
        internal static string SledDebugMenuStartComment {
            get {
                return ResourceManager.GetString("SledDebugMenuStartComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step &amp;Into.
        /// </summary>
        internal static string SledDebugMenuStep {
            get {
                return ResourceManager.GetString("SledDebugMenuStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step into a line.
        /// </summary>
        internal static string SledDebugMenuStepComment {
            get {
                return ResourceManager.GetString("SledDebugMenuStepComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step Ou&amp;t.
        /// </summary>
        internal static string SledDebugMenuStepOut {
            get {
                return ResourceManager.GetString("SledDebugMenuStepOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step out of a function.
        /// </summary>
        internal static string SledDebugMenuStepOutComment {
            get {
                return ResourceManager.GetString("SledDebugMenuStepOutComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step &amp;Over.
        /// </summary>
        internal static string SledDebugMenuStepOver {
            get {
                return ResourceManager.GetString("SledDebugMenuStepOver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step over a line.
        /// </summary>
        internal static string SledDebugMenuStepOverComment {
            get {
                return ResourceManager.GetString("SledDebugMenuStepOverComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sto&amp;p.
        /// </summary>
        internal static string SledDebugMenuStop {
            get {
                return ResourceManager.GetString("SledDebugMenuStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop debugging.
        /// </summary>
        internal static string SledDebugMenuStopComment {
            get {
                return ResourceManager.GetString("SledDebugMenuStopComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Debug.
        /// </summary>
        internal static string SledDebugMenuTitle {
            get {
                return ResourceManager.GetString("SledDebugMenuTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debugging Menu.
        /// </summary>
        internal static string SledDebugMenuTitleComment {
            get {
                return ResourceManager.GetString("SledDebugMenuTitleComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnected.
        /// </summary>
        internal static string SledDisconnected {
            get {
                return ResourceManager.GetString("SledDisconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File not sent! Breakpoints and other changes may be mis-matched!.
        /// </summary>
        internal static string SledEditAndContinueFileNotSentError {
            get {
                return ResourceManager.GetString("SledEditAndContinueFileNotSentError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to reload the updated file on the Target?.
        /// </summary>
        internal static string SledEditAndContinueReloadFileQuestion {
            get {
                return ResourceManager.GetString("SledEditAndContinueReloadFileQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit &amp; Continue.
        /// </summary>
        internal static string SledEditAndContinueTitle {
            get {
                return ResourceManager.GetString("SledEditAndContinueTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editor Locked.
        /// </summary>
        internal static string SledEditorLocked {
            get {
                return ResourceManager.GetString("SledEditorLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SLED has encountered an error and will close!.
        /// </summary>
        internal static string SledEncounterErrorWillCloseComment {
            get {
                return ResourceManager.GetString("SledEncounterErrorWillCloseComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string SledError {
            get {
                return ResourceManager.GetString("SledError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The error was: %s0.
        /// </summary>
        internal static string SledErrorWas {
            get {
                return ResourceManager.GetString("SledErrorWas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception was: %s0.
        /// </summary>
        internal static string SledExceptionWas {
            get {
                return ResourceManager.GetString("SledExceptionWas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SLED failed to change the file permissions!.
        /// </summary>
        internal static string SledFailChangePermissions {
            get {
                return ResourceManager.GetString("SledFailChangePermissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        internal static string SledFile {
            get {
                return ResourceManager.GetString("SledFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;File.
        /// </summary>
        internal static string SledFileMenu {
            get {
                return ResourceManager.GetString("SledFileMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File is read only!.
        /// </summary>
        internal static string SledFileReadOnly {
            get {
                return ResourceManager.GetString("SledFileReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Read Only - Error.
        /// </summary>
        internal static string SledFileReadOnlyError {
            get {
                return ResourceManager.GetString("SledFileReadOnlyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Displaying....
        /// </summary>
        internal static string SledFindAndReplaceDisplaying {
            get {
                return ResourceManager.GetString("SledFindAndReplaceDisplaying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Find &amp; Replace] No documents to search in!.
        /// </summary>
        internal static string SledFindAndReplaceErrorNoDocsToSearch {
            get {
                return ResourceManager.GetString("SledFindAndReplaceErrorNoDocsToSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Find &amp; Replace] Nothing found!.
        /// </summary>
        internal static string SledFindAndReplaceErrorNothingFound {
            get {
                return ResourceManager.GetString("SledFindAndReplaceErrorNothingFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gathering files....
        /// </summary>
        internal static string SledFindAndReplaceGatheringFiles {
            get {
                return ResourceManager.GetString("SledFindAndReplaceGatheringFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Open Documents.
        /// </summary>
        internal static string SledFindAndReplaceLookInAllOpenDocuments {
            get {
                return ResourceManager.GetString("SledFindAndReplaceLookInAllOpenDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Document.
        /// </summary>
        internal static string SledFindAndReplaceLookInCurrentDocument {
            get {
                return ResourceManager.GetString("SledFindAndReplaceLookInCurrentDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Project.
        /// </summary>
        internal static string SledFindAndReplaceLookInCurrentProject {
            get {
                return ResourceManager.GetString("SledFindAndReplaceLookInCurrentProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom.
        /// </summary>
        internal static string SledFindAndReplaceLookInCustom {
            get {
                return ResourceManager.GetString("SledFindAndReplaceLookInCustom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entire Solution.
        /// </summary>
        internal static string SledFindAndReplaceLookInEntireSolution {
            get {
                return ResourceManager.GetString("SledFindAndReplaceLookInEntireSolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replacing... %s0.
        /// </summary>
        internal static string SledFindAndReplaceReplacing {
            get {
                return ResourceManager.GetString("SledFindAndReplaceReplacing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searching... %s0.
        /// </summary>
        internal static string SledFindAndReplaceSearching {
            get {
                return ResourceManager.GetString("SledFindAndReplaceSearching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regular Expressions.
        /// </summary>
        internal static string SledFindAndReplaceUsePatternRegularExpressions {
            get {
                return ResourceManager.GetString("SledFindAndReplaceUsePatternRegularExpressions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wild Cards.
        /// </summary>
        internal static string SledFindAndReplaceUsePatternWildCards {
            get {
                return ResourceManager.GetString("SledFindAndReplaceUsePatternWildCards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find Results 1.
        /// </summary>
        internal static string SledFindResults1Title {
            get {
                return ResourceManager.GetString("SledFindResults1Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find Results 2.
        /// </summary>
        internal static string SledFindResults2Title {
            get {
                return ResourceManager.GetString("SledFindResults2Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception trying to jump to line number %s0 in file %s1: %s2.
        /// </summary>
        internal static string SledGotoLineError1 {
            get {
                return ResourceManager.GetString("SledGotoLineError1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception grabbing text from line %s0 in file %s1: %s2.
        /// </summary>
        internal static string SledGotoVariableError1 {
            get {
                return ResourceManager.GetString("SledGotoVariableError1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception reading file %s0 to find variable locations: %s1.
        /// </summary>
        internal static string SledGotoVariableError2 {
            get {
                return ResourceManager.GetString("SledGotoVariableError2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Help About Dialog] Exception: %s0.
        /// </summary>
        internal static string SledHelpAboutErrorException {
            get {
                return ResourceManager.GetString("SledHelpAboutErrorException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language Plugin: Loaded %s0 (%s1).
        /// </summary>
        internal static string SledLanguagePluginLoaded {
            get {
                return ResourceManager.GetString("SledLanguagePluginLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line.
        /// </summary>
        internal static string SledLine {
            get {
                return ResourceManager.GetString("SledLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encountered error when computing MD5 hash for file %s0! %s1.
        /// </summary>
        internal static string SledMD5FileError {
            get {
                return ResourceManager.GetString("SledMD5FileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network Plugin: Loaded %s0 (%s1).
        /// </summary>
        internal static string SledNetworkPluginLoaded {
            get {
                return ResourceManager.GetString("SledNetworkPluginLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;New.
        /// </summary>
        internal static string SledNew {
            get {
                return ResourceManager.GetString("SledNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string SledNone {
            get {
                return ResourceManager.GetString("SledNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occurrence.
        /// </summary>
        internal static string SledOccurrence {
            get {
                return ResourceManager.GetString("SledOccurrence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Open.
        /// </summary>
        internal static string SledOpen {
            get {
                return ResourceManager.GetString("SledOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path.
        /// </summary>
        internal static string SledPath {
            get {
                return ResourceManager.GetString("SledPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Files.
        /// </summary>
        internal static string SledProjectFilesTitle {
            get {
                return ResourceManager.GetString("SledProjectFilesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Project Files Tree] Error in label edit: %s0.
        /// </summary>
        internal static string SledProjectFilesTreeErrorLabelEditing {
            get {
                return ResourceManager.GetString("SledProjectFilesTreeErrorLabelEditing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Project Files Tree] Error attempting to rename file %s0: %s1.
        /// </summary>
        internal static string SledProjectFilesTreeErrorRenamingFile {
            get {
                return ResourceManager.GetString("SledProjectFilesTreeErrorRenamingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explore.
        /// </summary>
        internal static string SledProjectFilesTreeExplore {
            get {
                return ResourceManager.GetString("SledProjectFilesTreeExplore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navigate to item in explorer.
        /// </summary>
        internal static string SledProjectFilesTreeExploreComment {
            get {
                return ResourceManager.GetString("SledProjectFilesTreeExploreComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file does not exist!.
        /// </summary>
        internal static string SledProjectFilesTreeFileNotExist {
            get {
                return ResourceManager.GetString("SledProjectFilesTreeFileNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goto.
        /// </summary>
        internal static string SledProjectFilesTreeGoto {
            get {
                return ResourceManager.GetString("SledProjectFilesTreeGoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goto to item.
        /// </summary>
        internal static string SledProjectFilesTreeGotoComment {
            get {
                return ResourceManager.GetString("SledProjectFilesTreeGotoComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Folder.
        /// </summary>
        internal static string SledProjectFilesTreeNewFolder {
            get {
                return ResourceManager.GetString("SledProjectFilesTreeNewFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new folder.
        /// </summary>
        internal static string SledProjectFilesTreeNewFolderComment {
            get {
                return ResourceManager.GetString("SledProjectFilesTreeNewFolderComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        internal static string SledProjectFilesTreeOpen {
            get {
                return ResourceManager.GetString("SledProjectFilesTreeOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open item.
        /// </summary>
        internal static string SledProjectFilesTreeOpenComment {
            get {
                return ResourceManager.GetString("SledProjectFilesTreeOpenComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open With.
        /// </summary>
        internal static string SledProjectFilesTreeOpenWith {
            get {
                return ResourceManager.GetString("SledProjectFilesTreeOpenWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open with external program.
        /// </summary>
        internal static string SledProjectFilesTreeOpenWithComment {
            get {
                return ResourceManager.GetString("SledProjectFilesTreeOpenWithComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        internal static string SledProjectFilesTreeRemove {
            get {
                return ResourceManager.GetString("SledProjectFilesTreeRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove item.
        /// </summary>
        internal static string SledProjectFilesTreeRemoveComment {
            get {
                return ResourceManager.GetString("SledProjectFilesTreeRemoveComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename.
        /// </summary>
        internal static string SledProjectFilesTreeRename {
            get {
                return ResourceManager.GetString("SledProjectFilesTreeRename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename item.
        /// </summary>
        internal static string SledProjectFilesTreeRenameComment {
            get {
                return ResourceManager.GetString("SledProjectFilesTreeRenameComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle &amp;Breakpoint.
        /// </summary>
        internal static string SledProjectMenuToggleBreakpoint {
            get {
                return ResourceManager.GetString("SledProjectMenuToggleBreakpoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggles a breakpoint on/off.
        /// </summary>
        internal static string SledProjectMenuToggleBreakpointComment {
            get {
                return ResourceManager.GetString("SledProjectMenuToggleBreakpointComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug: No project open error! Possible reasons: 1) no project open in SLED or 2a) no project details were specified by the Target or 2b) the Target specified wrong paths for its project details or 2c) directory creation failed due to windows permission settings..
        /// </summary>
        internal static string SledRemoteTargetErrorNoProjectOpen {
            get {
                return ResourceManager.GetString("SledRemoteTargetErrorNoProjectOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug: Script cache error! File does not exist: %s0 (%s1).
        /// </summary>
        internal static string SledRemoteTargetErrorScriptCacheFileNotExist {
            get {
                return ResourceManager.GetString("SledRemoteTargetErrorScriptCacheFileNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Remote Target] Error selecting target %s0: %s1.
        /// </summary>
        internal static string SledRemoteTargetErrorSelectingTarget {
            get {
                return ResourceManager.GetString("SledRemoteTargetErrorSelectingTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No targets - do you wish to add some?.
        /// </summary>
        internal static string SledRemoteTargetErrorString {
            get {
                return ResourceManager.GetString("SledRemoteTargetErrorString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remote Target Error.
        /// </summary>
        internal static string SledRemoteTargetErrorTitle {
            get {
                return ResourceManager.GetString("SledRemoteTargetErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Remote Target] Error updating the ComboBox: %s0.
        /// </summary>
        internal static string SledRemoteTargetErrorUpdatingComboBox {
            get {
                return ResourceManager.GetString("SledRemoteTargetErrorUpdatingComboBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug: Version mismatch - SLED %s0.%s1 supports a range of versions from %s2.%s3-%s0.%s1 but the Target&apos;s version is %s4.%s5!.
        /// </summary>
        internal static string SledRemoteTargetErrorVersionMismatch {
            get {
                return ResourceManager.GetString("SledRemoteTargetErrorVersionMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remote Targets.
        /// </summary>
        internal static string SledRemoteTargetsComboBoxDefault {
            get {
                return ResourceManager.GetString("SledRemoteTargetsComboBoxDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception loading %s0 settings: %s1.
        /// </summary>
        internal static string SledSettingsErrorExceptionLoadingSetting {
            get {
                return ResourceManager.GetString("SledSettingsErrorExceptionLoadingSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception saving %s0 settings: %s1.
        /// </summary>
        internal static string SledSettingsErrorExceptionSavingSetting {
            get {
                return ResourceManager.GetString("SledSettingsErrorExceptionSavingSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Syntax check finished!.
        /// </summary>
        internal static string SledSyntaxCheckFinished {
            get {
                return ResourceManager.GetString("SledSyntaxCheckFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Syntax check starting....
        /// </summary>
        internal static string SledSyntaxCheckStarting {
            get {
                return ResourceManager.GetString("SledSyntaxCheckStarting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Syntax Errors.
        /// </summary>
        internal static string SledSyntaxErrorsTitle {
            get {
                return ResourceManager.GetString("SledSyntaxErrorsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug: Connecting to %s0.
        /// </summary>
        internal static string SledTargetConnectingTo {
            get {
                return ResourceManager.GetString("SledTargetConnectingTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug: Negotiation timed out.
        /// </summary>
        internal static string SledTargetConnectionErrorNegotiating {
            get {
                return ResourceManager.GetString("SledTargetConnectionErrorNegotiating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug: Connection established to %s0.
        /// </summary>
        internal static string SledTargetConnectionEstablishedTo {
            get {
                return ResourceManager.GetString("SledTargetConnectionEstablishedTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug: Negotiating connection with %s0.
        /// </summary>
        internal static string SledTargetConnectionNegotiating {
            get {
                return ResourceManager.GetString("SledTargetConnectionNegotiating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug: Disconnected from %s0.
        /// </summary>
        internal static string SledTargetDisconnectedFrom {
            get {
                return ResourceManager.GetString("SledTargetDisconnectedFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: No project open! Either open an existing project or set the target up to relay project information to SLED (by using SCEA::LibLuaDebugger::SetSledProjectInfo())..
        /// </summary>
        internal static string SledTargetErrorNoProjectOpen {
            get {
                return ResourceManager.GetString("SledTargetErrorNoProjectOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug: Error processing server message! Message was:.
        /// </summary>
        internal static string SledTargetErrorProcessingMessage {
            get {
                return ResourceManager.GetString("SledTargetErrorProcessingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting to a host with unknown endianness; disconnecting!.
        /// </summary>
        internal static string SledTargetErrorUnknownEndianness {
            get {
                return ResourceManager.GetString("SledTargetErrorUnknownEndianness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug: No response from target....
        /// </summary>
        internal static string SledTargetHeartBeatNoResponse {
            get {
                return ResourceManager.GetString("SledTargetHeartBeatNoResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Manage Targets.
        /// </summary>
        internal static string SledTargetMenuManageTargets {
            get {
                return ResourceManager.GetString("SledTargetMenuManageTargets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage remote targets.
        /// </summary>
        internal static string SledTargetMenuManageTargetsComment {
            get {
                return ResourceManager.GetString("SledTargetMenuManageTargetsComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Target.
        /// </summary>
        internal static string SledTargetMenuTitle {
            get {
                return ResourceManager.GetString("SledTargetMenuTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target Menu.
        /// </summary>
        internal static string SledTargetMenuTitleComment {
            get {
                return ResourceManager.GetString("SledTargetMenuTitleComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug: Ready to debug %s0.
        /// </summary>
        internal static string SledTargetReady {
            get {
                return ResourceManager.GetString("SledTargetReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug: Start.
        /// </summary>
        internal static string SledTargetStartCmd {
            get {
                return ResourceManager.GetString("SledTargetStartCmd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug: Step Into.
        /// </summary>
        internal static string SledTargetStepIntoCmd {
            get {
                return ResourceManager.GetString("SledTargetStepIntoCmd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug: Step Out.
        /// </summary>
        internal static string SledTargetStepOutcmd {
            get {
                return ResourceManager.GetString("SledTargetStepOutcmd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug: Step Over.
        /// </summary>
        internal static string SledTargetStepOverCmd {
            get {
                return ResourceManager.GetString("SledTargetStepOverCmd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug: Stop.
        /// </summary>
        internal static string SledTargetStopCmd {
            get {
                return ResourceManager.GetString("SledTargetStopCmd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        internal static string SledText {
            get {
                return ResourceManager.GetString("SledText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TT&amp;Y.
        /// </summary>
        internal static string SledTTY {
            get {
                return ResourceManager.GetString("SledTTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Clear TTY Window.
        /// </summary>
        internal static string SledTTYClearTTYWindow {
            get {
                return ResourceManager.GetString("SledTTYClearTTYWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear the TTY window.
        /// </summary>
        internal static string SledTTYClearTTYWindowComment {
            get {
                return ResourceManager.GetString("SledTTYClearTTYWindowComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid language selection! Message not sent. Please select a valid language from the combobox..
        /// </summary>
        internal static string SledTTYErrorInvalidLanguage {
            get {
                return ResourceManager.GetString("SledTTYErrorInvalidLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No language plugins have been registered with the TTY service therefore no messages can be sent via TTY..
        /// </summary>
        internal static string SledTTYErrorNoLanguagesRegistered {
            get {
                return ResourceManager.GetString("SledTTYErrorNoLanguagesRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TTY Error.
        /// </summary>
        internal static string SledTTYErrorTitle {
            get {
                return ResourceManager.GetString("SledTTYErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TTY Filter.
        /// </summary>
        internal static string SledTTYFilter {
            get {
                return ResourceManager.GetString("SledTTYFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No TTY filter entries to save!.
        /// </summary>
        internal static string SledTTYFilterEntriesSave {
            get {
                return ResourceManager.GetString("SledTTYFilterEntriesSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error loading file: %s0.
        /// </summary>
        internal static string SledTTYFilterErrorLoadingFile {
            get {
                return ResourceManager.GetString("SledTTYFilterErrorLoadingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error writing file: %s0.
        /// </summary>
        internal static string SledTTYFilterErrorWritingFile {
            get {
                return ResourceManager.GetString("SledTTYFilterErrorWritingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TTY Filter - File Error.
        /// </summary>
        internal static string SledTTYFilterFileError {
            get {
                return ResourceManager.GetString("SledTTYFilterFileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No TTYFilter nodes found in file: %s0.
        /// </summary>
        internal static string SledTTYFilterNoNodesFoundInFile {
            get {
                return ResourceManager.GetString("SledTTYFilterNoNodesFoundInFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Filter TTY Output.
        /// </summary>
        internal static string SledTTYFilterTTYOutput {
            get {
                return ResourceManager.GetString("SledTTYFilterTTYOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bring up the TTY filter form.
        /// </summary>
        internal static string SledTTYFilterTTYOutputComment {
            get {
                return ResourceManager.GetString("SledTTYFilterTTYOutputComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TTY Options.
        /// </summary>
        internal static string SledTTYOptions {
            get {
                return ResourceManager.GetString("SledTTYOptions", resourceCulture);
            }
        }
    }
}
