//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sce.Sled.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sce.Sled.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *.
        /// </summary>
        internal static string Asterisk {
            get {
                return ResourceManager.GetString("Asterisk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *;.
        /// </summary>
        internal static string AsteriskSemicolon {
            get {
                return ResourceManager.GetString("AsteriskSemicolon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [BP] Continue (%s0:%s1).
        /// </summary>
        internal static string BreakpointContinue {
            get {
                return ResourceManager.GetString("BreakpointContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BP line number -1!.
        /// </summary>
        internal static string BreakpointErrorLineNegativeOne {
            get {
                return ResourceManager.GetString("BreakpointErrorLineNegativeOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [BP] Stopped (%s0:%s1).
        /// </summary>
        internal static string BreakpointStopped {
            get {
                return ResourceManager.GetString("BreakpointStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to :.
        /// </summary>
        internal static string Colon {
            get {
                return ResourceManager.GetString("Colon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to , .
        /// </summary>
        internal static string CommaSpace {
            get {
                return ResourceManager.GetString("CommaSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -.
        /// </summary>
        internal static string Dash {
            get {
                return ResourceManager.GetString("Dash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug.
        /// </summary>
        internal static string Debug {
            get {
                return ResourceManager.GetString("Debug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SledFindResults1.
        /// </summary>
        internal static string DomFindResults1List {
            get {
                return ResourceManager.GetString("DomFindResults1List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SledFindResults2.
        /// </summary>
        internal static string DomFindResults2List {
            get {
                return ResourceManager.GetString("DomFindResults2List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SledSyntaxErrors.
        /// </summary>
        internal static string DomSyntaxErrorsList {
            get {
                return ResourceManager.GetString("DomSyntaxErrorsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to expanded.
        /// </summary>
        internal static string ExpandedLower {
            get {
                return ResourceManager.GetString("ExpandedLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FindAndReplaceSettings.
        /// </summary>
        internal static string FindAndReplaceSettings {
            get {
                return ResourceManager.GetString("FindAndReplaceSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find and replace settings.
        /// </summary>
        internal static string FindAndReplaceSettingsComment {
            get {
                return ResourceManager.GetString("FindAndReplaceSettingsComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find and Replace Settings.
        /// </summary>
        internal static string FindAndReplaceSettingsTitle {
            get {
                return ResourceManager.GetString("FindAndReplaceSettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to findresults1.xml.
        /// </summary>
        internal static string FindResults1FileName {
            get {
                return ResourceManager.GetString("FindResults1FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to findresults2.xml.
        /// </summary>
        internal static string FindResults2FileName {
            get {
                return ResourceManager.GetString("FindResults2FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {B35EF4F2-5BC6-5CC6-9C41-463EEC6C5B6A}.
        /// </summary>
        internal static string GuidFindAndReplaceSettings {
            get {
                return ResourceManager.GetString("GuidFindAndReplaceSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {B35AF4F2-8BB4-4cd4-5C41-33364E6F5B6A}.
        /// </summary>
        internal static string GuidHeartbeat {
            get {
                return ResourceManager.GetString("GuidHeartbeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {B35EA4E2-5EE7-5CC6-9D41-341EEE6C5B6B}.
        /// </summary>
        internal static string GuidLuaPlugin {
            get {
                return ResourceManager.GetString("GuidLuaPlugin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {B35AB4F6-8BB3-4cd3-5C41-33364E6F7B9A}.
        /// </summary>
        internal static string GuidSyntaxCheckerState {
            get {
                return ResourceManager.GetString("GuidSyntaxCheckerState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {E39AC4F6-7FC2-4cd3-8C91-26164E6F7B9A}.
        /// </summary>
        internal static string GuidTTYFilters {
            get {
                return ResourceManager.GetString("GuidTTYFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heartbeat.
        /// </summary>
        internal static string Heartbeat {
            get {
                return ResourceManager.GetString("Heartbeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heartbeat state.
        /// </summary>
        internal static string HeartbeatStateComment {
            get {
                return ResourceManager.GetString("HeartbeatStateComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heartbeat State.
        /// </summary>
        internal static string HeartbeatStateTitle {
            get {
                return ResourceManager.GetString("HeartbeatStateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sce.Sled.Resources.About.rtf.
        /// </summary>
        internal static string HelpAboutAssemblyPath {
            get {
                return ResourceManager.GetString("HelpAboutAssemblyPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SLED - Script Language Editor and Debugger - %s0.
        /// </summary>
        internal static string HelpAboutTitleWithVersion {
            get {
                return ResourceManager.GetString("HelpAboutTitleWithVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .ico.
        /// </summary>
        internal static string IcoExtension {
            get {
                return ResourceManager.GetString("IcoExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {.
        /// </summary>
        internal static string LeftSquiggly {
            get {
                return ResourceManager.GetString("LeftSquiggly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LuaPlugin.
        /// </summary>
        internal static string LuaPlugin {
            get {
                return ResourceManager.GetString("LuaPlugin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ShowUserMessage.
        /// </summary>
        internal static string LuaPluginCheckerShowUserMessage {
            get {
                return ResourceManager.GetString("LuaPluginCheckerShowUserMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ShowUserMessageTitle.
        /// </summary>
        internal static string LuaPluginCheckerShowUserMessageTitle {
            get {
                return ResourceManager.GetString("LuaPluginCheckerShowUserMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /.
        /// </summary>
        internal static string MenuSeparator {
            get {
                return ResourceManager.GetString("MenuSeparator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NetworkPlugin.
        /// </summary>
        internal static string NetworkPlugin {
            get {
                return ResourceManager.GetString("NetworkPlugin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to null.
        /// </summary>
        internal static string NullLower {
            get {
                return ResourceManager.GetString("NullLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        internal static string One {
            get {
                return ResourceManager.GetString("One", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.0.
        /// </summary>
        internal static string OnePointZero {
            get {
                return ResourceManager.GetString("OnePointZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to path.
        /// </summary>
        internal static string PathLower {
            get {
                return ResourceManager.GetString("PathLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ..
        /// </summary>
        internal static string Period {
            get {
                return ResourceManager.GetString("Period", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to |.
        /// </summary>
        internal static string Pipe {
            get {
                return ResourceManager.GetString("Pipe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .png.
        /// </summary>
        internal static string PngExtension {
            get {
                return ResourceManager.GetString("PngExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project.
        /// </summary>
        internal static string Project {
            get {
                return ResourceManager.GetString("Project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .lpf.
        /// </summary>
        internal static string ProjectFileExtensionLpf {
            get {
                return ResourceManager.GetString("ProjectFileExtensionLpf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .spf.
        /// </summary>
        internal static string ProjectFileExtensionSpf {
            get {
                return ResourceManager.GetString("ProjectFileExtensionSpf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .sus.
        /// </summary>
        internal static string ProjectTempFileExtensionSus {
            get {
                return ResourceManager.GetString("ProjectTempFileExtensionSus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remote Targets.
        /// </summary>
        internal static string RemoteTargets {
            get {
                return ResourceManager.GetString("RemoteTargets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to )|.
        /// </summary>
        internal static string RightParenthesisPipe {
            get {
                return ResourceManager.GetString("RightParenthesisPipe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to )|*.
        /// </summary>
        internal static string RightParenthesisPipeAsterisk {
            get {
                return ResourceManager.GetString("RightParenthesisPipeAsterisk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to }.
        /// </summary>
        internal static string RightSquiggly {
            get {
                return ResourceManager.GetString("RightSquiggly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected.
        /// </summary>
        internal static string Selected {
            get {
                return ResourceManager.GetString("Selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SLED.
        /// </summary>
        internal static string SLED {
            get {
                return ResourceManager.GetString("SLED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SledTarget.
        /// </summary>
        internal static string SledTarget {
            get {
                return ResourceManager.GetString("SledTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SledTargets.
        /// </summary>
        internal static string SledTargets {
            get {
                return ResourceManager.GetString("SledTargets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Script Language Editor and Debugger.
        /// </summary>
        internal static string SLEDTitle {
            get {
                return ResourceManager.GetString("SLEDTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  .
        /// </summary>
        internal static string Space {
            get {
                return ResourceManager.GetString("Space", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  (*.
        /// </summary>
        internal static string SpaceLeftParenthesisAsterisk {
            get {
                return ResourceManager.GetString("SpaceLeftParenthesisAsterisk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SyntaxChecker.
        /// </summary>
        internal static string SyntaxChecker {
            get {
                return ResourceManager.GetString("SyntaxChecker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SyntaxCheckerState.
        /// </summary>
        internal static string SyntaxCheckerState {
            get {
                return ResourceManager.GetString("SyntaxCheckerState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Syntax Checker State.
        /// </summary>
        internal static string SyntaxCheckerStateTitle {
            get {
                return ResourceManager.GetString("SyntaxCheckerStateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to syntaxerrors.xml.
        /// </summary>
        internal static string SyntaxErrorsFileName {
            get {
                return ResourceManager.GetString("SyntaxErrorsFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Syntax Errors.
        /// </summary>
        internal static string SyntaxErrorsTitle {
            get {
                return ResourceManager.GetString("SyntaxErrorsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target.
        /// </summary>
        internal static string Target {
            get {
                return ResourceManager.GetString("Target", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TTY.
        /// </summary>
        internal static string TTY {
            get {
                return ResourceManager.GetString("TTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TTYFilter.
        /// </summary>
        internal static string TTYFilter {
            get {
                return ResourceManager.GetString("TTYFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of TTY filters.
        /// </summary>
        internal static string TTYFilterListComment {
            get {
                return ResourceManager.GetString("TTYFilterListComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TTY Filter List.
        /// </summary>
        internal static string TTYFilterListTitle {
            get {
                return ResourceManager.GetString("TTYFilterListTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TtyFilters.
        /// </summary>
        internal static string TTYFilters {
            get {
                return ResourceManager.GetString("TTYFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .txt.
        /// </summary>
        internal static string TxtExtension {
            get {
                return ResourceManager.GetString("TxtExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to utf-8.
        /// </summary>
        internal static string UtfDashEight {
            get {
                return ResourceManager.GetString("UtfDashEight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yes.
        /// </summary>
        internal static string YesLower {
            get {
                return ResourceManager.GetString("YesLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.
        /// </summary>
        internal static string Zero {
            get {
                return ResourceManager.GetString("Zero", resourceCulture);
            }
        }
    }
}
