//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sce.Sled.Shared.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sce.Sled.Shared.Resources.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Files....
        /// </summary>
        internal static string SledAddFiles {
            get {
                return ResourceManager.GetString("SledAddFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add files to the project.
        /// </summary>
        internal static string SledAddFilesToProject {
            get {
                return ResourceManager.GetString("SledAddFilesToProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explore.
        /// </summary>
        internal static string SledExplore {
            get {
                return ResourceManager.GetString("SledExplore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Read Only.
        /// </summary>
        internal static string SledFileReadOnly {
            get {
                return ResourceManager.GetString("SledFileReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Read Only - Error.
        /// </summary>
        internal static string SledFileReadOnlyError {
            get {
                return ResourceManager.GetString("SledFileReadOnlyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to ignore future .spf/.lpf related read-only file errors?.
        /// </summary>
        internal static string SledIgnoreReadOnlyErrors {
            get {
                return ResourceManager.GetString("SledIgnoreReadOnlyErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Folder.
        /// </summary>
        internal static string SledNewFolder {
            get {
                return ResourceManager.GetString("SledNewFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string SledNone {
            get {
                return ResourceManager.GetString("SledNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open with another program.
        /// </summary>
        internal static string SledOpenAnotherProgram {
            get {
                return ResourceManager.GetString("SledOpenAnotherProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open File.
        /// </summary>
        internal static string SledOpenFile {
            get {
                return ResourceManager.GetString("SledOpenFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open With....
        /// </summary>
        internal static string SledOpenWith {
            get {
                return ResourceManager.GetString("SledOpenWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %s0 is read only! Would you like to overwrite this property and make the file writable?.
        /// </summary>
        internal static string SledOverwriteReadOnly {
            get {
                return ResourceManager.GetString("SledOverwriteReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question.
        /// </summary>
        internal static string SledQuestion {
            get {
                return ResourceManager.GetString("SledQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove File.
        /// </summary>
        internal static string SledRemoveFile {
            get {
                return ResourceManager.GetString("SledRemoveFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove file from project.
        /// </summary>
        internal static string SledRemoveFileFromProject {
            get {
                return ResourceManager.GetString("SledRemoveFileFromProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Folder.
        /// </summary>
        internal static string SledRemoveFolder {
            get {
                return ResourceManager.GetString("SledRemoveFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename File.
        /// </summary>
        internal static string SledRenameFile {
            get {
                return ResourceManager.GetString("SledRenameFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename Folder.
        /// </summary>
        internal static string SledRenameFolder {
            get {
                return ResourceManager.GetString("SledRenameFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        internal static string SledSend {
            get {
                return ResourceManager.GetString("SledSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average.
        /// </summary>
        internal static string SledSharedAverage {
            get {
                return ResourceManager.GetString("SledSharedAverage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average (Inner).
        /// </summary>
        internal static string SledSharedAverageInner {
            get {
                return ResourceManager.GetString("SledSharedAverageInner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calls.
        /// </summary>
        internal static string SledSharedCalls {
            get {
                return ResourceManager.GetString("SledSharedCalls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Condition.
        /// </summary>
        internal static string SledSharedCondition {
            get {
                return ResourceManager.GetString("SledSharedCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cond. Enabled.
        /// </summary>
        internal static string SledSharedConditionEnabled {
            get {
                return ResourceManager.GetString("SledSharedConditionEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled.
        /// </summary>
        internal static string SledSharedEnabled {
            get {
                return ResourceManager.GetString("SledSharedEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string SledSharedError {
            get {
                return ResourceManager.GetString("SledSharedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The error was: %s0.
        /// </summary>
        internal static string SledSharedErrorWas {
            get {
                return ResourceManager.GetString("SledSharedErrorWas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        internal static string SledSharedFile {
            get {
                return ResourceManager.GetString("SledSharedFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Function.
        /// </summary>
        internal static string SledSharedFunction {
            get {
                return ResourceManager.GetString("SledSharedFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goto function.
        /// </summary>
        internal static string SledSharedGotoFunctionComment {
            get {
                return ResourceManager.GetString("SledSharedGotoFunctionComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goto Function.
        /// </summary>
        internal static string SledSharedGotoFunctionTitle {
            get {
                return ResourceManager.GetString("SledSharedGotoFunctionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string SledSharedLanguage {
            get {
                return ResourceManager.GetString("SledSharedLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line.
        /// </summary>
        internal static string SledSharedLine {
            get {
                return ResourceManager.GetString("SledSharedLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encountered an error when loading temporary settings file! %s0.
        /// </summary>
        internal static string SledSharedLoadTempSettingsFileError {
            get {
                return ResourceManager.GetString("SledSharedLoadTempSettingsFileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Longest.
        /// </summary>
        internal static string SledSharedLongest {
            get {
                return ResourceManager.GetString("SledSharedLongest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Longest (Inner).
        /// </summary>
        internal static string SledSharedLongestInner {
            get {
                return ResourceManager.GetString("SledSharedLongestInner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MD5 Hash.
        /// </summary>
        internal static string SledSharedMD5Hash {
            get {
                return ResourceManager.GetString("SledSharedMD5Hash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Address.
        /// </summary>
        internal static string SledSharedNewAddress {
            get {
                return ResourceManager.GetString("SledSharedNewAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Size.
        /// </summary>
        internal static string SledSharedNewSize {
            get {
                return ResourceManager.GetString("SledSharedNewSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old Address.
        /// </summary>
        internal static string SledSharedOldAddress {
            get {
                return ResourceManager.GetString("SledSharedOldAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old Size.
        /// </summary>
        internal static string SledSharedOldSize {
            get {
                return ResourceManager.GetString("SledSharedOldSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order.
        /// </summary>
        internal static string SledSharedOrder {
            get {
                return ResourceManager.GetString("SledSharedOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path.
        /// </summary>
        internal static string SledSharedPath {
            get {
                return ResourceManager.GetString("SledSharedPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result.
        /// </summary>
        internal static string SledSharedResult {
            get {
                return ResourceManager.GetString("SledSharedResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encountered an error when saving temporary settings file! %s0.
        /// </summary>
        internal static string SledSharedSaveTempSettingsFileError {
            get {
                return ResourceManager.GetString("SledSharedSaveTempSettingsFileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shortest.
        /// </summary>
        internal static string SledSharedShortest {
            get {
                return ResourceManager.GetString("SledSharedShortest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shortest (Inner).
        /// </summary>
        internal static string SledSharedShortestInner {
            get {
                return ResourceManager.GetString("SledSharedShortestInner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        internal static string SledSharedTotal {
            get {
                return ResourceManager.GetString("SledSharedTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total (Inner).
        /// </summary>
        internal static string SledSharedTotalInner {
            get {
                return ResourceManager.GetString("SledSharedTotalInner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What.
        /// </summary>
        internal static string SledSharedWhat {
            get {
                return ResourceManager.GetString("SledSharedWhat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TTY service has already been set.
        /// </summary>
        internal static string SledTTYServiceAlreadySet {
            get {
                return ResourceManager.GetString("SledTTYServiceAlreadySet", resourceCulture);
            }
        }
    }
}
