//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sce.Sled.Project.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sce.Sled.Project.Resources.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Add File.
        /// </summary>
        internal static string SledAddFile {
            get {
                return ResourceManager.GetString("SledAddFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asset directory does not exist! Would you like to set a new asset directory?.
        /// </summary>
        internal static string SledAssetDirectoryErrorDoesNotExist {
            get {
                return ResourceManager.GetString("SledAssetDirectoryErrorDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No asset directory set, files will probably not open!.
        /// </summary>
        internal static string SledAssetDirectoryErrorNotSet {
            get {
                return ResourceManager.GetString("SledAssetDirectoryErrorNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asset Directory Error.
        /// </summary>
        internal static string SledAssetDirectoryErrorTitle {
            get {
                return ResourceManager.GetString("SledAssetDirectoryErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the asset directory!.
        /// </summary>
        internal static string SledAssetDirectorySelect {
            get {
                return ResourceManager.GetString("SledAssetDirectorySelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files Found (%s0 Files) (%s1 Checked).
        /// </summary>
        internal static string SledAutoAddFilesCount {
            get {
                return ResourceManager.GetString("SledAutoAddFilesCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto project creation did not find the asset directory specified but was able to create the new directory %s0..
        /// </summary>
        internal static string SledAutoProjectCreationErrorNotFindAssetDir1 {
            get {
                return ResourceManager.GetString("SledAutoProjectCreationErrorNotFindAssetDir1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto project creation failed to find and then create an asset directory! The directory was %s0 and the error was %s0..
        /// </summary>
        internal static string SledAutoProjectCreationErrorNotFindAssetDir2 {
            get {
                return ResourceManager.GetString("SledAutoProjectCreationErrorNotFindAssetDir2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto project creation did not find the project directory specified but was able to create the new directory %s0..
        /// </summary>
        internal static string SledAutoProjectCreationErrorNotFindProjectDir1 {
            get {
                return ResourceManager.GetString("SledAutoProjectCreationErrorNotFindProjectDir1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto project creation failed to find and then create a project directory! The directory was %s0 and the error was %s1..
        /// </summary>
        internal static string SledAutoProjectCreationErrorNotFindProjectDir2 {
            get {
                return ResourceManager.GetString("SledAutoProjectCreationErrorNotFindProjectDir2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Close.
        /// </summary>
        internal static string SledClose {
            get {
                return ResourceManager.GetString("SledClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a file to the project.
        /// </summary>
        internal static string SledCommandProjectAddFileComment {
            get {
                return ResourceManager.GetString("SledCommandProjectAddFileComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close an open project.
        /// </summary>
        internal static string SledCommandProjectCloseComment {
            get {
                return ResourceManager.GetString("SledCommandProjectCloseComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new project.
        /// </summary>
        internal static string SledCommandProjectNewComment {
            get {
                return ResourceManager.GetString("SledCommandProjectNewComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open an existing project.
        /// </summary>
        internal static string SledCommandProjectOpenComment {
            get {
                return ResourceManager.GetString("SledCommandProjectOpenComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Save Project.
        /// </summary>
        internal static string SledCommandProjectSave {
            get {
                return ResourceManager.GetString("SledCommandProjectSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Project A&amp;s....
        /// </summary>
        internal static string SledCommandProjectSaveAs {
            get {
                return ResourceManager.GetString("SledCommandProjectSaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save project as....
        /// </summary>
        internal static string SledCommandProjectSaveAsComment {
            get {
                return ResourceManager.GetString("SledCommandProjectSaveAsComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save project.
        /// </summary>
        internal static string SledCommandProjectSaveComment {
            get {
                return ResourceManager.GetString("SledCommandProjectSaveComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;File.
        /// </summary>
        internal static string SledFile {
            get {
                return ResourceManager.GetString("SledFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        internal static string SledFileNoAmpersand {
            get {
                return ResourceManager.GetString("SledFileNoAmpersand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encountered error when computing MD5 hash for file %s0! %s1.
        /// </summary>
        internal static string SledMD5FileError {
            get {
                return ResourceManager.GetString("SledMD5FileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;New.
        /// </summary>
        internal static string SledNew {
            get {
                return ResourceManager.GetString("SledNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Open.
        /// </summary>
        internal static string SledOpen {
            get {
                return ResourceManager.GetString("SledOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path.
        /// </summary>
        internal static string SledPath {
            get {
                return ResourceManager.GetString("SledPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Project.
        /// </summary>
        internal static string SledProject {
            get {
                return ResourceManager.GetString("SledProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Files Error.
        /// </summary>
        internal static string SledProjectAutoAddFilesAddFilesErrorTitle {
            get {
                return ResourceManager.GetString("SledProjectAutoAddFilesAddFilesErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an exception when trying to find files recursively from %s0.
        /// </summary>
        internal static string SledProjectAutoAddFilesAddFilesException {
            get {
                return ResourceManager.GetString("SledProjectAutoAddFilesAddFilesException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a directory to add files from!.
        /// </summary>
        internal static string SledProjectAutoAddFilesSelectDirTitle {
            get {
                return ResourceManager.GetString("SledProjectAutoAddFilesSelectDirTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to save?.
        /// </summary>
        internal static string SledProjectDirtyString {
            get {
                return ResourceManager.GetString("SledProjectDirtyString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Dirty!.
        /// </summary>
        internal static string SledProjectDirtyTitle {
            get {
                return ResourceManager.GetString("SledProjectDirtyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encountered an error removing the read-only attribute of the project file when trying to verify that the namespace was correct and that there were no duplicate entries..
        /// </summary>
        internal static string SledProjectFileReadOnlyRemoveError {
            get {
                return ResourceManager.GetString("SledProjectFileReadOnlyRemoveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encountered an error &quot;%s0&quot; when removing duplicates from project file %s1.
        /// </summary>
        internal static string SledProjectFilesErrorRemovingDuplicates {
            get {
                return ResourceManager.GetString("SledProjectFilesErrorRemovingDuplicates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encountered an error &quot;%s0&quot; when verifying namespace in project file %s1.
        /// </summary>
        internal static string SledProjectFilesErrorVerifyingNamespace {
            get {
                return ResourceManager.GetString("SledProjectFilesErrorVerifyingNamespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Files.
        /// </summary>
        internal static string SledProjectFilesTitle {
            get {
                return ResourceManager.GetString("SledProjectFilesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Change Asset Directory.
        /// </summary>
        internal static string SledProjectMenuChangeAssetDir {
            get {
                return ResourceManager.GetString("SledProjectMenuChangeAssetDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change asset directory.
        /// </summary>
        internal static string SledProjectMenuChangeAssetDirComment {
            get {
                return ResourceManager.GetString("SledProjectMenuChangeAssetDirComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Clear Output Window.
        /// </summary>
        internal static string SledProjectMenuClearOutputWindow {
            get {
                return ResourceManager.GetString("SledProjectMenuClearOutputWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear the output window.
        /// </summary>
        internal static string SledProjectMenuClearOutputWindowComment {
            get {
                return ResourceManager.GetString("SledProjectMenuClearOutputWindowComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Last Project On Startup.
        /// </summary>
        internal static string SledProjectMenuOpenLast {
            get {
                return ResourceManager.GetString("SledProjectMenuOpenLast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open the last used project on startup.
        /// </summary>
        internal static string SledProjectMenuOpenLastComment {
            get {
                return ResourceManager.GetString("SledProjectMenuOpenLastComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Files....
        /// </summary>
        internal static string SledProjectMenuShowAutoAddFilesComment {
            get {
                return ResourceManager.GetString("SledProjectMenuShowAutoAddFilesComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Add Files....
        /// </summary>
        internal static string SledProjectMenuShowAutoAddFilesTitle {
            get {
                return ResourceManager.GetString("SledProjectMenuShowAutoAddFilesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perform Syntax Check.
        /// </summary>
        internal static string SledProjectMenuSyntaxCheck {
            get {
                return ResourceManager.GetString("SledProjectMenuSyntaxCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checks scripts for syntax errors.
        /// </summary>
        internal static string SledProjectMenuSyntaxCheckComment {
            get {
                return ResourceManager.GetString("SledProjectMenuSyntaxCheckComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle Syntax Check.
        /// </summary>
        internal static string SledProjectMenuSyntaxCheckState {
            get {
                return ResourceManager.GetString("SledProjectMenuSyntaxCheckState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle Syntax Check On/Off.
        /// </summary>
        internal static string SledProjectMenuSyntaxCheckStateComment {
            get {
                return ResourceManager.GetString("SledProjectMenuSyntaxCheckStateComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Project.
        /// </summary>
        internal static string SledProjectMenuTitle {
            get {
                return ResourceManager.GetString("SledProjectMenuTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General Project Options.
        /// </summary>
        internal static string SledProjectMenuTitleComment {
            get {
                return ResourceManager.GetString("SledProjectMenuTitleComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;View Project Paths.
        /// </summary>
        internal static string SledProjectMenuViewProjectPaths {
            get {
                return ResourceManager.GetString("SledProjectMenuViewProjectPaths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View project paths.
        /// </summary>
        internal static string SledProjectMenuViewProjectPathsComment {
            get {
                return ResourceManager.GetString("SledProjectMenuViewProjectPathsComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a folder to be the asset folder!.
        /// </summary>
        internal static string SledProjectNewFormAssetDirSelectDescription {
            get {
                return ResourceManager.GetString("SledProjectNewFormAssetDirSelectDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid asset directory!.
        /// </summary>
        internal static string SledProjectNewFormErrorAssetDir {
            get {
                return ResourceManager.GetString("SledProjectNewFormErrorAssetDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid project directory!.
        /// </summary>
        internal static string SledProjectNewFormErrorProjectDir {
            get {
                return ResourceManager.GetString("SledProjectNewFormErrorProjectDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid project name!.
        /// </summary>
        internal static string SledProjectNewFormErrorProjectName {
            get {
                return ResourceManager.GetString("SledProjectNewFormErrorProjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Project Form - Error.
        /// </summary>
        internal static string SledProjectNewFormErrorTitle {
            get {
                return ResourceManager.GetString("SledProjectNewFormErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a folder to create the project in!.
        /// </summary>
        internal static string SledProjectNewFormProjectDirSelectDescription {
            get {
                return ResourceManager.GetString("SledProjectNewFormProjectDirSelectDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The project file does not exist! Would you like to remove the entry from the most recent project list?.
        /// </summary>
        internal static string SledProjectOpenErrorString1 {
            get {
                return ResourceManager.GetString("SledProjectOpenErrorString1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Open Error.
        /// </summary>
        internal static string SledProjectOpenErrorTitle {
            get {
                return ResourceManager.GetString("SledProjectOpenErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent Project.
        /// </summary>
        internal static string SledRecentProject {
            get {
                return ResourceManager.GetString("SledRecentProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open a recently used project.
        /// </summary>
        internal static string SledRecentProjectComment {
            get {
                return ResourceManager.GetString("SledRecentProjectComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent &amp;Projects.
        /// </summary>
        internal static string SledRecentProjects {
            get {
                return ResourceManager.GetString("SledRecentProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Remove File.
        /// </summary>
        internal static string SledRemoveFile {
            get {
                return ResourceManager.GetString("SledRemoveFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove file from project.
        /// </summary>
        internal static string SledRemoveFileComment {
            get {
                return ResourceManager.GetString("SledRemoveFileComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception loading %s0 settings: %s1.
        /// </summary>
        internal static string SledSettingsErrorExceptionLoadingSetting {
            get {
                return ResourceManager.GetString("SledSettingsErrorExceptionLoadingSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception saving %s0 settings: %s1.
        /// </summary>
        internal static string SledSettingsErrorExceptionSavingSetting {
            get {
                return ResourceManager.GetString("SledSettingsErrorExceptionSavingSetting", resourceCulture);
            }
        }
    }
}
