//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sce.Sled.Project.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sce.Sled.Project.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to , .
        /// </summary>
        internal static string CommaSpace {
            get {
                return ResourceManager.GetString("CommaSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SledProjectFiles.
        /// </summary>
        internal static string DomProjectFilesList {
            get {
                return ResourceManager.GetString("DomProjectFilesList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to expanded.
        /// </summary>
        internal static string ExpandedLower {
            get {
                return ResourceManager.GetString("ExpandedLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {B35eF4F2-7BB4-4ed4-9C41-66634E6C5B6A}.
        /// </summary>
        internal static string GuidLastProjectOnStartup {
            get {
                return ResourceManager.GetString("GuidLastProjectOnStartup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {E39AB3F6-8FC2-4cd3-9C95-26164B6E7B9C}.
        /// </summary>
        internal static string GuidMruProjects {
            get {
                return ResourceManager.GetString("GuidMruProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (1).
        /// </summary>
        internal static string MenuItem1 {
            get {
                return ResourceManager.GetString("MenuItem1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (2).
        /// </summary>
        internal static string MenuItem2 {
            get {
                return ResourceManager.GetString("MenuItem2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (3).
        /// </summary>
        internal static string MenuItem3 {
            get {
                return ResourceManager.GetString("MenuItem3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (4).
        /// </summary>
        internal static string MenuItem4 {
            get {
                return ResourceManager.GetString("MenuItem4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /.
        /// </summary>
        internal static string MenuSeparator {
            get {
                return ResourceManager.GetString("MenuSeparator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MruProject.
        /// </summary>
        internal static string MruProject {
            get {
                return ResourceManager.GetString("MruProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Most recently used projects list.
        /// </summary>
        internal static string MruProjectListComment {
            get {
                return ResourceManager.GetString("MruProjectListComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mru Project List.
        /// </summary>
        internal static string MruProjectListTitle {
            get {
                return ResourceManager.GetString("MruProjectListTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MruProjects.
        /// </summary>
        internal static string MruProjects {
            get {
                return ResourceManager.GetString("MruProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        internal static string One {
            get {
                return ResourceManager.GetString("One", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.0.
        /// </summary>
        internal static string OnePointZero {
            get {
                return ResourceManager.GetString("OnePointZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OpenLast.
        /// </summary>
        internal static string OpenLast {
            get {
                return ResourceManager.GetString("OpenLast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OpenLastProjectOnStartup.
        /// </summary>
        internal static string OpenLastProjectOnStartup {
            get {
                return ResourceManager.GetString("OpenLastProjectOnStartup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open last project on startup.
        /// </summary>
        internal static string OpenLastProjectOnStartupTitle {
            get {
                return ResourceManager.GetString("OpenLastProjectOnStartupTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OpenLastProjectOnStartupToggle.
        /// </summary>
        internal static string OpenLastProjectOnStartupToggle {
            get {
                return ResourceManager.GetString("OpenLastProjectOnStartupToggle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open the last used project on SLED startup.
        /// </summary>
        internal static string OpenLastProjectOnStartupToggleDescription {
            get {
                return ResourceManager.GetString("OpenLastProjectOnStartupToggleDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Last Project.
        /// </summary>
        internal static string OpenLastProjectOnStartupToggleTitle {
            get {
                return ResourceManager.GetString("OpenLastProjectOnStartupToggleTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to path.
        /// </summary>
        internal static string PathLower {
            get {
                return ResourceManager.GetString("PathLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project.
        /// </summary>
        internal static string Project {
            get {
                return ResourceManager.GetString("Project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .lpf.
        /// </summary>
        internal static string ProjectFileExtensionLpf {
            get {
                return ResourceManager.GetString("ProjectFileExtensionLpf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .spf.
        /// </summary>
        internal static string ProjectFileExtensionSpf {
            get {
                return ResourceManager.GetString("ProjectFileExtensionSpf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Files.
        /// </summary>
        internal static string ProjectFiles {
            get {
                return ResourceManager.GetString("ProjectFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .sus.
        /// </summary>
        internal static string ProjectTempFileExtensionSus {
            get {
                return ResourceManager.GetString("ProjectTempFileExtensionSus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  .
        /// </summary>
        internal static string Space {
            get {
                return ResourceManager.GetString("Space", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to utf-8.
        /// </summary>
        internal static string UtfDashEight {
            get {
                return ResourceManager.GetString("UtfDashEight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yes.
        /// </summary>
        internal static string YesLower {
            get {
                return ResourceManager.GetString("YesLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.
        /// </summary>
        internal static string Zero {
            get {
                return ResourceManager.GetString("Zero", resourceCulture);
            }
        }
    }
}
