//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sce.Sled.Lua.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sce.Sled.Lua.Resources.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Environment Table Variable Watch.
        /// </summary>
        internal static string SledLuaAddEnvVarWatch {
            get {
                return ResourceManager.GetString("SledLuaAddEnvVarWatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add environment table variable to the Lua watch list.
        /// </summary>
        internal static string SledLuaAddEnvVarWatchComment {
            get {
                return ResourceManager.GetString("SledLuaAddEnvVarWatchComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Local Watch.
        /// </summary>
        internal static string SledLuaAddLocalWatch {
            get {
                return ResourceManager.GetString("SledLuaAddLocalWatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add local variable to the Lua watch list.
        /// </summary>
        internal static string SledLuaAddLocalWatchComment {
            get {
                return ResourceManager.GetString("SledLuaAddLocalWatchComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Upvalue Watch.
        /// </summary>
        internal static string SledLuaAddUpvalueWatch {
            get {
                return ResourceManager.GetString("SledLuaAddUpvalueWatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add upvalue variable to the Lua watch list.
        /// </summary>
        internal static string SledLuaAddUpvalueWatchComment {
            get {
                return ResourceManager.GetString("SledLuaAddUpvalueWatchComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lua Call Stack.
        /// </summary>
        internal static string SledLuaCallStackTitle {
            get {
                return ResourceManager.GetString("SledLuaCallStackTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call Stack.
        /// </summary>
        internal static string SledLuaCallStackTitleShort {
            get {
                return ResourceManager.GetString("SledLuaCallStackTitleShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lua Compiler.
        /// </summary>
        internal static string SledLuaCompiler {
            get {
                return ResourceManager.GetString("SledLuaCompiler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compile.
        /// </summary>
        internal static string SledLuaCompilerCompile {
            get {
                return ResourceManager.GetString("SledLuaCompilerCompile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compile Lua scripts.
        /// </summary>
        internal static string SledLuaCompilerCompileComment {
            get {
                return ResourceManager.GetString("SledLuaCompilerCompileComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Lua compiler] Can&apos;t compile script to user supplied destination directory because the directory doesn&apos;t exist and can&apos;t be created! The exception was: %s0.
        /// </summary>
        internal static string SledLuaCompilerErrorCantCreateDir {
            get {
                return ResourceManager.GetString("SledLuaCompilerErrorCantCreateDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Lua compiler] Exception compiling file %s0: %s1.
        /// </summary>
        internal static string SledLuaCompilerErrorExceptionCompilingFile {
            get {
                return ResourceManager.GetString("SledLuaCompilerErrorExceptionCompilingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Lua compiler] Exception with Lua compiler: %s0.
        /// </summary>
        internal static string SledLuaCompilerErrorExceptionInLuaCompiler {
            get {
                return ResourceManager.GetString("SledLuaCompilerErrorExceptionInLuaCompiler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Lua compiler] Compiling %s0: failed! %s1.
        /// </summary>
        internal static string SledLuaCompilerErrorFailed {
            get {
                return ResourceManager.GetString("SledLuaCompilerErrorFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Lua compiler] No active project; nothing to compile!.
        /// </summary>
        internal static string SledLuaCompilerErrorNoActiveProject {
            get {
                return ResourceManager.GetString("SledLuaCompilerErrorNoActiveProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Lua compiler] No files to compile!.
        /// </summary>
        internal static string SledLuaCompilerErrorNoFiles {
            get {
                return ResourceManager.GetString("SledLuaCompilerErrorNoFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Lua compiler] No files owned by Lua plugin; nothing to compile!.
        /// </summary>
        internal static string SledLuaCompilerErrorNoPluginOwnedFiles {
            get {
                return ResourceManager.GetString("SledLuaCompilerErrorNoPluginOwnedFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Lua compiler] Compiling %s0: success!.
        /// </summary>
        internal static string SledLuaCompilerErrorSuccess {
            get {
                return ResourceManager.GetString("SledLuaCompilerErrorSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have no compiler configurations or have not selected a compiler configuration to use. You will now be prompted to select a compiler configuration..
        /// </summary>
        internal static string SledLuaCompilerNotifySelectConfiguration {
            get {
                return ResourceManager.GetString("SledLuaCompilerNotifySelectConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have no compiler configurations or have not selected a compiler configuration to use - compilation cannot continue..
        /// </summary>
        internal static string SledLuaCompilerNotifySelectConfigurationError {
            get {
                return ResourceManager.GetString("SledLuaCompilerNotifySelectConfigurationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compiler Settings.
        /// </summary>
        internal static string SledLuaCompilerSettings {
            get {
                return ResourceManager.GetString("SledLuaCompilerSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify Lua compiler settings.
        /// </summary>
        internal static string SledLuaCompilerSettingsComment {
            get {
                return ResourceManager.GetString("SledLuaCompilerSettingsComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new Lua file.
        /// </summary>
        internal static string SledLuaCreateNewFileComment {
            get {
                return ResourceManager.GetString("SledLuaCreateNewFileComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lua Environment.
        /// </summary>
        internal static string SledLuaEnvironmentTitle {
            get {
                return ResourceManager.GetString("SledLuaEnvironmentTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Environment.
        /// </summary>
        internal static string SledLuaEnvironmentTitleShort {
            get {
                return ResourceManager.GetString("SledLuaEnvironmentTitleShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string SledLuaError {
            get {
                return ResourceManager.GetString("SledLuaError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception: %s0.
        /// </summary>
        internal static string SledLuaExceptionTag {
            get {
                return ResourceManager.GetString("SledLuaExceptionTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception was: %s0.
        /// </summary>
        internal static string SledLuaExceptionWas {
            get {
                return ResourceManager.GetString("SledLuaExceptionWas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %s0 failed to find base table!.
        /// </summary>
        internal static string SledLuaFailedToFindBase {
            get {
                return ResourceManager.GetString("SledLuaFailedToFindBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;File.
        /// </summary>
        internal static string SledLuaFile {
            get {
                return ResourceManager.GetString("SledLuaFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter &amp;Environment Table Variables.
        /// </summary>
        internal static string SledLuaFilterEnvVarVars {
            get {
                return ResourceManager.GetString("SledLuaFilterEnvVarVars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter environment table variables.
        /// </summary>
        internal static string SledLuaFilterEnvVarVarsComment {
            get {
                return ResourceManager.GetString("SledLuaFilterEnvVarVarsComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter &amp;Global Variables.
        /// </summary>
        internal static string SledLuaFilterGlobalVars {
            get {
                return ResourceManager.GetString("SledLuaFilterGlobalVars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter global variables.
        /// </summary>
        internal static string SledLuaFilterGlobalVarsComment {
            get {
                return ResourceManager.GetString("SledLuaFilterGlobalVarsComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter &amp;Local Variables.
        /// </summary>
        internal static string SledLuaFilterLocalVars {
            get {
                return ResourceManager.GetString("SledLuaFilterLocalVars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter local variables.
        /// </summary>
        internal static string SledLuaFilterLocalVarsComment {
            get {
                return ResourceManager.GetString("SledLuaFilterLocalVarsComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter &amp;Upvalue Variables.
        /// </summary>
        internal static string SledLuaFilterUpvalueVars {
            get {
                return ResourceManager.GetString("SledLuaFilterUpvalueVars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter upvalue variables.
        /// </summary>
        internal static string SledLuaFilterUpvalueVarsComments {
            get {
                return ResourceManager.GetString("SledLuaFilterUpvalueVarsComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Function.
        /// </summary>
        internal static string SledLuaFunction {
            get {
                return ResourceManager.GetString("SledLuaFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lua Globals.
        /// </summary>
        internal static string SledLuaGlobalsTitle {
            get {
                return ResourceManager.GetString("SledLuaGlobalsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Globals.
        /// </summary>
        internal static string SledLuaGlobalsTitleShort {
            get {
                return ResourceManager.GetString("SledLuaGlobalsTitleShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goto Global.
        /// </summary>
        internal static string SledLuaGotoGlobal {
            get {
                return ResourceManager.GetString("SledLuaGotoGlobal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to where the global is used.
        /// </summary>
        internal static string SledLuaGotoGlobalComment {
            get {
                return ResourceManager.GetString("SledLuaGotoGlobalComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goto Local.
        /// </summary>
        internal static string SledLuaGotoLocal {
            get {
                return ResourceManager.GetString("SledLuaGotoLocal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to where the local is used.
        /// </summary>
        internal static string SledLuaGotoLocalComment {
            get {
                return ResourceManager.GetString("SledLuaGotoLocalComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goto Upvalue.
        /// </summary>
        internal static string SledLuaGotoUpvalue {
            get {
                return ResourceManager.GetString("SledLuaGotoUpvalue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to where the upvalue is used.
        /// </summary>
        internal static string SledLuaGotoUpvalueComment {
            get {
                return ResourceManager.GetString("SledLuaGotoUpvalueComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Global Watch.
        /// </summary>
        internal static string SledLuaGotoWatch {
            get {
                return ResourceManager.GetString("SledLuaGotoWatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add global variable to the Lua watch list.
        /// </summary>
        internal static string SledLuaGotoWatchComment {
            get {
                return ResourceManager.GetString("SledLuaGotoWatchComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you liked to ignore read-only file errors?.
        /// </summary>
        internal static string SledLuaIgnoreReadOnlyErrors {
            get {
                return ResourceManager.GetString("SledLuaIgnoreReadOnlyErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lua Locals.
        /// </summary>
        internal static string SledLuaLocalsTitle {
            get {
                return ResourceManager.GetString("SledLuaLocalsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locals.
        /// </summary>
        internal static string SledLuaLocalsTitleShort {
            get {
                return ResourceManager.GetString("SledLuaLocalsTitleShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lua scripting language.
        /// </summary>
        internal static string SledLuaLuaLanguageDescription {
            get {
                return ResourceManager.GetString("SledLuaLuaLanguageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lua State (0x%s0).
        /// </summary>
        internal static string SledLuaLuaState {
            get {
                return ResourceManager.GetString("SledLuaLuaState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        internal static string SledLuaLuaStateAddress {
            get {
                return ResourceManager.GetString("SledLuaLuaStateAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled.
        /// </summary>
        internal static string SledLuaLuaStateEnabled {
            get {
                return ResourceManager.GetString("SledLuaLuaStateEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string SledLuaLuaStateName {
            get {
                return ResourceManager.GetString("SledLuaLuaStateName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lua States.
        /// </summary>
        internal static string SledLuaLuaStates {
            get {
                return ResourceManager.GetString("SledLuaLuaStates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allocation.
        /// </summary>
        internal static string SledLuaMemoryTraceAlloc {
            get {
                return ResourceManager.GetString("SledLuaMemoryTraceAlloc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deallocation.
        /// </summary>
        internal static string SledLuaMemoryTraceDealloc {
            get {
                return ResourceManager.GetString("SledLuaMemoryTraceDealloc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reallocation.
        /// </summary>
        internal static string SledLuaMemoryTraceRealloc {
            get {
                return ResourceManager.GetString("SledLuaMemoryTraceRealloc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug: Error in memory trace streaming [%s0].
        /// </summary>
        internal static string SledLuaMemoryTraceStreamingError {
            get {
                return ResourceManager.GetString("SledLuaMemoryTraceStreamingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lua Memory Trace.
        /// </summary>
        internal static string SledLuaMemoryTraceTitle {
            get {
                return ResourceManager.GetString("SledLuaMemoryTraceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Memory Trace.
        /// </summary>
        internal static string SledLuaMemoryTraceTitleShort {
            get {
                return ResourceManager.GetString("SledLuaMemoryTraceTitleShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug: Cannot modify Lua globals/locals/upvalues at this time!.
        /// </summary>
        internal static string SledLuaModifyVarInvalidTime {
            get {
                return ResourceManager.GetString("SledLuaModifyVarInvalidTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug: Can only modify variables of type: LUA_TBOOLEAN, LUA_TNUMBER, or LUA_TSTRING!.
        /// </summary>
        internal static string SledLuaModifyVarInvalidType {
            get {
                return ResourceManager.GetString("SledLuaModifyVarInvalidType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug: Invalid value %s0 for type LUA_TNUMBER. Must be a number!.
        /// </summary>
        internal static string SledLuaModifyVarInvalidValue1 {
            get {
                return ResourceManager.GetString("SledLuaModifyVarInvalidValue1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug: Invalid value %s0 for type LUA_TBOOLEAN. Must be true/false/1/0.
        /// </summary>
        internal static string SledLuaModifyVarInvalidValue2 {
            get {
                return ResourceManager.GetString("SledLuaModifyVarInvalidValue2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug: Modification sent.
        /// </summary>
        internal static string SledLuaModifyVarSent {
            get {
                return ResourceManager.GetString("SledLuaModifyVarSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string SledLuaName {
            get {
                return ResourceManager.GetString("SledLuaName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;New.
        /// </summary>
        internal static string SledLuaNew {
            get {
                return ResourceManager.GetString("SledLuaNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %s0 is read only! Would you like to overwrite this property and make the file writable?.
        /// </summary>
        internal static string SledLuaOverwriteReadOnly {
            get {
                return ResourceManager.GetString("SledLuaOverwriteReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lua Plugin Options.
        /// </summary>
        internal static string SledLuaPluginOptions {
            get {
                return ResourceManager.GetString("SledLuaPluginOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lua Profile Function Calls Tree.
        /// </summary>
        internal static string SledLuaProfileFuncCallsTitle {
            get {
                return ResourceManager.GetString("SledLuaProfileFuncCallsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile Function Calls Tree.
        /// </summary>
        internal static string SledLuaProfileFuncCallsTitleShort {
            get {
                return ResourceManager.GetString("SledLuaProfileFuncCallsTitleShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lua Profile Info.
        /// </summary>
        internal static string SledLuaProfileInfoTitle {
            get {
                return ResourceManager.GetString("SledLuaProfileInfoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile Info.
        /// </summary>
        internal static string SledLuaProfileInfoTitleShort {
            get {
                return ResourceManager.GetString("SledLuaProfileInfoTitleShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question.
        /// </summary>
        internal static string SledLuaQuestion {
            get {
                return ResourceManager.GetString("SledLuaQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug: Error processing server message! Message was:.
        /// </summary>
        internal static string SledLuaRemoteTargetMessageError {
            get {
                return ResourceManager.GetString("SledLuaRemoteTargetMessageError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Environment Table Variable Watch(es).
        /// </summary>
        internal static string SledLuaRemoveEnvVarWatches {
            get {
                return ResourceManager.GetString("SledLuaRemoveEnvVarWatches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove environment table variable(s) from the Lua watch list.
        /// </summary>
        internal static string SledLuaRemoveEnvVarWatchesComment {
            get {
                return ResourceManager.GetString("SledLuaRemoveEnvVarWatchesComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Global Watch(es).
        /// </summary>
        internal static string SledLuaRemoveGlobalWatches {
            get {
                return ResourceManager.GetString("SledLuaRemoveGlobalWatches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove global variable(s) from the Lua watch list.
        /// </summary>
        internal static string SledLuaRemoveGlobalWatchesComment {
            get {
                return ResourceManager.GetString("SledLuaRemoveGlobalWatchesComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Local Watch(es).
        /// </summary>
        internal static string SledLuaRemoveLocalWatches {
            get {
                return ResourceManager.GetString("SledLuaRemoveLocalWatches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove local variable(s) from the Lua watch list.
        /// </summary>
        internal static string SledLuaRemoveLocalWatchesComment {
            get {
                return ResourceManager.GetString("SledLuaRemoveLocalWatchesComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Selected Watches.
        /// </summary>
        internal static string SledLuaRemoveSelectedWatches {
            get {
                return ResourceManager.GetString("SledLuaRemoveSelectedWatches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove selected variables from the Lua watch list.
        /// </summary>
        internal static string SledLuaRemoveSelectedWatchesComment {
            get {
                return ResourceManager.GetString("SledLuaRemoveSelectedWatchesComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Upvalue Watch(es).
        /// </summary>
        internal static string SledLuaRemoveUpvalueWatches {
            get {
                return ResourceManager.GetString("SledLuaRemoveUpvalueWatches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove upvalue variable(s) from the Lua watch list.
        /// </summary>
        internal static string SledLuaRemoveUpvalueWatchesComment {
            get {
                return ResourceManager.GetString("SledLuaRemoveUpvalueWatchesComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lua: Sending updated variable network filter state.
        /// </summary>
        internal static string SledLuaSendNetVarFilterState {
            get {
                return ResourceManager.GetString("SledLuaSendNetVarFilterState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lua Syntax Checker: Failed to create instance!.
        /// </summary>
        internal static string SledLuaSyntaxCheckerErrorInstance {
            get {
                return ResourceManager.GetString("SledLuaSyntaxCheckerErrorInstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lua Syntax Checker: Failed to create instance! Exception was: %s0.
        /// </summary>
        internal static string SledLuaSyntaxCheckerErrorInstanceWithException {
            get {
                return ResourceManager.GetString("SledLuaSyntaxCheckerErrorInstanceWithException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lua Syntax Checker: Exception processing file %s0! Exception was: %s1.
        /// </summary>
        internal static string SledLuaSyntaxCheckerErrorProcessingFile {
            get {
                return ResourceManager.GetString("SledLuaSyntaxCheckerErrorProcessingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lua Syntax Checker: Exception processing string %s0! Exception was: %s1.
        /// </summary>
        internal static string SledLuaSyntaxCheckerErrorProcessingString {
            get {
                return ResourceManager.GetString("SledLuaSyntaxCheckerErrorProcessingString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Lua.
        /// </summary>
        internal static string SledLuaTag {
            get {
                return ResourceManager.GetString("SledLuaTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle Lua &amp;Profiler.
        /// </summary>
        internal static string SledLuaToggleLuaProfiler {
            get {
                return ResourceManager.GetString("SledLuaToggleLuaProfiler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggles the Lua profiler on/off.
        /// </summary>
        internal static string SledLuaToggleLuaProfilerComment {
            get {
                return ResourceManager.GetString("SledLuaToggleLuaProfilerComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle Lua &amp;Memory Tracer.
        /// </summary>
        internal static string SledLuaToggleMemoryTracer {
            get {
                return ResourceManager.GetString("SledLuaToggleMemoryTracer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggles the Lua memory tracer on/off.
        /// </summary>
        internal static string SledLuaToggleMemoryTracerComment {
            get {
                return ResourceManager.GetString("SledLuaToggleMemoryTracerComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string SledLuaTTYFilterAdd {
            get {
                return ResourceManager.GetString("SledLuaTTYFilterAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string SledLuaTTYFilterEdit {
            get {
                return ResourceManager.GetString("SledLuaTTYFilterEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string SledLuaType {
            get {
                return ResourceManager.GetString("SledLuaType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lua Upvalues.
        /// </summary>
        internal static string SledLuaUpvaluesTitle {
            get {
                return ResourceManager.GetString("SledLuaUpvaluesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upvalues.
        /// </summary>
        internal static string SledLuaUpvaluesTitleShort {
            get {
                return ResourceManager.GetString("SledLuaUpvaluesTitleShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        internal static string SledLuaValue {
            get {
                return ResourceManager.GetString("SledLuaValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lua Environment Table Variable Filter.
        /// </summary>
        internal static string SledLuaVariableFilterEnvVarTitle {
            get {
                return ResourceManager.GetString("SledLuaVariableFilterEnvVarTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lua Global Variable Filter.
        /// </summary>
        internal static string SledLuaVariableFilterGlobalTitle {
            get {
                return ResourceManager.GetString("SledLuaVariableFilterGlobalTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lua Local Variable Filter.
        /// </summary>
        internal static string SledLuaVariableFilterLocalTitle {
            get {
                return ResourceManager.GetString("SledLuaVariableFilterLocalTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lua Upvalue Variable Filter.
        /// </summary>
        internal static string SledLuaVariableFilterUpvalueTitle {
            get {
                return ResourceManager.GetString("SledLuaVariableFilterUpvalueTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lua Variable Parser: Complete!.
        /// </summary>
        internal static string SledLuaVarParserComplete {
            get {
                return ResourceManager.GetString("SledLuaVarParserComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lua Variable Parser: Failed to load .dll!.
        /// </summary>
        internal static string SledLuaVarParserDllLoadFailed {
            get {
                return ResourceManager.GetString("SledLuaVarParserDllLoadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variable Parser: Failed to create instance!.
        /// </summary>
        internal static string SledLuaVarParserErrorInstance {
            get {
                return ResourceManager.GetString("SledLuaVarParserErrorInstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variable Parser: Failed to create instance! Exception was: %s0.
        /// </summary>
        internal static string SledLuaVarParserErrorInstanceWithException {
            get {
                return ResourceManager.GetString("SledLuaVarParserErrorInstanceWithException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lua Variable Parser: Failed parsing %s0!.
        /// </summary>
        internal static string SledLuaVarParserFailedParsing {
            get {
                return ResourceManager.GetString("SledLuaVarParserFailedParsing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lua Variable Parser: %s0: found valid breakpoint position on line %s1!.
        /// </summary>
        internal static string SledLuaVarParserFoundBp {
            get {
                return ResourceManager.GetString("SledLuaVarParserFoundBp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lua Variable Parser: %s0: found function %s1 at line %s2!.
        /// </summary>
        internal static string SledLuaVarParserFoundFunc {
            get {
                return ResourceManager.GetString("SledLuaVarParserFoundFunc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lua Variable Parser: %s0: found %s1 on line %s2!.
        /// </summary>
        internal static string SledLuaVarParserFoundVar {
            get {
                return ResourceManager.GetString("SledLuaVarParserFoundVar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lua Variable Parser: Starting....
        /// </summary>
        internal static string SledLuaVarParserStarting {
            get {
                return ResourceManager.GetString("SledLuaVarParserStarting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lua Variable Parser: %s0.
        /// </summary>
        internal static string SledLuaVarParserWithArg {
            get {
                return ResourceManager.GetString("SledLuaVarParserWithArg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lua watch &quot;%s0&quot; format incorrect, removing!.
        /// </summary>
        internal static string SledLuaWatchFormatIncorrect {
            get {
                return ResourceManager.GetString("SledLuaWatchFormatIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lua Watch List.
        /// </summary>
        internal static string SledLuaWatchListTitle {
            get {
                return ResourceManager.GetString("SledLuaWatchListTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Watch List.
        /// </summary>
        internal static string SledLuaWatchListTitleShort {
            get {
                return ResourceManager.GetString("SledLuaWatchListTitleShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception loading %s0 settings: %s1.
        /// </summary>
        internal static string SledSettingsErrorExceptionLoadingSetting {
            get {
                return ResourceManager.GetString("SledSettingsErrorExceptionLoadingSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception saving %s0 settings: %s1.
        /// </summary>
        internal static string SledSettingsErrorExceptionSavingSetting {
            get {
                return ResourceManager.GetString("SledSettingsErrorExceptionSavingSetting", resourceCulture);
            }
        }
    }
}
