//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sce.Sled.Lua.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sce.Sled.Lua.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 16x16.
        /// </summary>
        internal static string _16x16 {
            get {
                return ResourceManager.GetString("_16x16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *.
        /// </summary>
        internal static string Asterisk {
            get {
                return ResourceManager.GetString("Asterisk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lua-callstack.xml.
        /// </summary>
        internal static string CallstackFileName {
            get {
                return ResourceManager.GetString("CallstackFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CheckBuffer.
        /// </summary>
        internal static string CheckBuffer {
            get {
                return ResourceManager.GetString("CheckBuffer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to :.
        /// </summary>
        internal static string Colon {
            get {
                return ResourceManager.GetString("Colon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ,.
        /// </summary>
        internal static string Comma {
            get {
                return ResourceManager.GetString("Comma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SledLuaCallStack.
        /// </summary>
        internal static string DomCallStackList {
            get {
                return ResourceManager.GetString("DomCallStackList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SledLuaVarEnvList.
        /// </summary>
        internal static string DomEnvVarList {
            get {
                return ResourceManager.GetString("DomEnvVarList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SledLuaVarGlobals.
        /// </summary>
        internal static string DomGlobalsList {
            get {
                return ResourceManager.GetString("DomGlobalsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SledLuaVarLocals.
        /// </summary>
        internal static string DomLocalsList {
            get {
                return ResourceManager.GetString("DomLocalsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SledLuaStatesList.
        /// </summary>
        internal static string DomLuaStatesList {
            get {
                return ResourceManager.GetString("DomLuaStatesList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SledLuaMemoryTrace.
        /// </summary>
        internal static string DomMemoryTraceList {
            get {
                return ResourceManager.GetString("DomMemoryTraceList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DomObject isn&apos;t a watched variable!.
        /// </summary>
        internal static string DomObjectIsntWatchedVar {
            get {
                return ResourceManager.GetString("DomObjectIsntWatchedVar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SledLuaProfileFuncCalls.
        /// </summary>
        internal static string DomProfileFuncCallsList {
            get {
                return ResourceManager.GetString("DomProfileFuncCallsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SledLuaProfileInfo.
        /// </summary>
        internal static string DomProfileInfoList {
            get {
                return ResourceManager.GetString("DomProfileInfoList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SledLuaVarUpvalues.
        /// </summary>
        internal static string DomUpvaluesList {
            get {
                return ResourceManager.GetString("DomUpvaluesList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SledLuaVarWatchList.
        /// </summary>
        internal static string DomWatchedVarsList {
            get {
                return ResourceManager.GetString("DomWatchedVarsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E.
        /// </summary>
        internal static string E {
            get {
                return ResourceManager.GetString("E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e.
        /// </summary>
        internal static string ELower {
            get {
                return ResourceManager.GetString("ELower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EnvVar.
        /// </summary>
        internal static string EnvVar {
            get {
                return ResourceManager.GetString("EnvVar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EnvVars.
        /// </summary>
        internal static string EnvVars {
            get {
                return ResourceManager.GetString("EnvVars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to envvars.
        /// </summary>
        internal static string EnvVarsLower {
            get {
                return ResourceManager.GetString("EnvVarsLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to False.
        /// </summary>
        internal static string False {
            get {
                return ResourceManager.GetString("False", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to G.
        /// </summary>
        internal static string G {
            get {
                return ResourceManager.GetString("G", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global.
        /// </summary>
        internal static string Global {
            get {
                return ResourceManager.GetString("Global", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Globals.
        /// </summary>
        internal static string Globals {
            get {
                return ResourceManager.GetString("Globals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lua-globals.xml.
        /// </summary>
        internal static string GlobalsFileName {
            get {
                return ResourceManager.GetString("GlobalsFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to g.
        /// </summary>
        internal static string GLower {
            get {
                return ResourceManager.GetString("GLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {E39AB3F6-8FD3-5cd3-1C11-11264E6E7B9C}.
        /// </summary>
        internal static string GuidLuaCompilerService {
            get {
                return ResourceManager.GetString("GuidLuaCompilerService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {E39AB3F6-8EEE-EEEE-1D11-11264E6E7B9C}.
        /// </summary>
        internal static string GuidLuaFunctionParserService {
            get {
                return ResourceManager.GetString("GuidLuaFunctionParserService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {E39EDDD6-AAAA-1234-1A23-11264E6E7B9C}.
        /// </summary>
        internal static string GuidLuaVariableParserService {
            get {
                return ResourceManager.GetString("GuidLuaVariableParserService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0x.
        /// </summary>
        internal static string HexAddress {
            get {
                return ResourceManager.GetString("HexAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Lua version!.
        /// </summary>
        internal static string InvalidLuaVersion {
            get {
                return ResourceManager.GetString("InvalidLuaVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L.
        /// </summary>
        internal static string L {
            get {
                return ResourceManager.GetString("L", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to l.
        /// </summary>
        internal static string LLower {
            get {
                return ResourceManager.GetString("LLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local.
        /// </summary>
        internal static string Local {
            get {
                return ResourceManager.GetString("Local", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locals.
        /// </summary>
        internal static string Locals {
            get {
                return ResourceManager.GetString("Locals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to locals.
        /// </summary>
        internal static string LocalsLower {
            get {
                return ResourceManager.GetString("LocalsLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lua.
        /// </summary>
        internal static string Lua {
            get {
                return ResourceManager.GetString("Lua", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LUA_TBOOLEAN.
        /// </summary>
        internal static string LUA_TBOOLEAN {
            get {
                return ResourceManager.GetString("LUA_TBOOLEAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LUA_TFUNCTION.
        /// </summary>
        internal static string LUA_TFUNCTION {
            get {
                return ResourceManager.GetString("LUA_TFUNCTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LUA_TLIGHTUSERDATA.
        /// </summary>
        internal static string LUA_TLIGHTUSERDATA {
            get {
                return ResourceManager.GetString("LUA_TLIGHTUSERDATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LUA_TNIL.
        /// </summary>
        internal static string LUA_TNIL {
            get {
                return ResourceManager.GetString("LUA_TNIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LUA_TNONE.
        /// </summary>
        internal static string LUA_TNONE {
            get {
                return ResourceManager.GetString("LUA_TNONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LUA_TNUMBER.
        /// </summary>
        internal static string LUA_TNUMBER {
            get {
                return ResourceManager.GetString("LUA_TNUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LUA_TSTRING.
        /// </summary>
        internal static string LUA_TSTRING {
            get {
                return ResourceManager.GetString("LUA_TSTRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LUA_TTABLE.
        /// </summary>
        internal static string LUA_TTABLE {
            get {
                return ResourceManager.GetString("LUA_TTABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LUA_TTHREAD.
        /// </summary>
        internal static string LUA_TTHREAD {
            get {
                return ResourceManager.GetString("LUA_TTHREAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LUA_TUSERDATA.
        /// </summary>
        internal static string LUA_TUSERDATA {
            get {
                return ResourceManager.GetString("LUA_TUSERDATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lua Call Stack.
        /// </summary>
        internal static string LuaCallStack {
            get {
                return ResourceManager.GetString("LuaCallStack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LuaCompilerSettings.
        /// </summary>
        internal static string LuaCompilerSettings {
            get {
                return ResourceManager.GetString("LuaCompilerSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lua Compiler Settings.
        /// </summary>
        internal static string LuaCompilerSettingsTitle {
            get {
                return ResourceManager.GetString("LuaCompilerSettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lua Environment Variables.
        /// </summary>
        internal static string LuaEnvironmentVariables {
            get {
                return ResourceManager.GetString("LuaEnvironmentVariables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .lua.
        /// </summary>
        internal static string LuaExtension {
            get {
                return ResourceManager.GetString("LuaExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lua Function Parser.
        /// </summary>
        internal static string LuaFunctionParser {
            get {
                return ResourceManager.GetString("LuaFunctionParser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LuaFunctionParserSettings.
        /// </summary>
        internal static string LuaFunctionParserSettings {
            get {
                return ResourceManager.GetString("LuaFunctionParserSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lua Function Parser Settings.
        /// </summary>
        internal static string LuaFunctionParserSettingsTitle {
            get {
                return ResourceManager.GetString("LuaFunctionParserSettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lua Globals.
        /// </summary>
        internal static string LuaGlobals {
            get {
                return ResourceManager.GetString("LuaGlobals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lua Locals.
        /// </summary>
        internal static string LuaLocals {
            get {
                return ResourceManager.GetString("LuaLocals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lua Memory Trace.
        /// </summary>
        internal static string LuaMemoryTrace {
            get {
                return ResourceManager.GetString("LuaMemoryTrace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lua Profile Func Calls.
        /// </summary>
        internal static string LuaProfileFuncCalls {
            get {
                return ResourceManager.GetString("LuaProfileFuncCalls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lua Profile Info.
        /// </summary>
        internal static string LuaProfileInfo {
            get {
                return ResourceManager.GetString("LuaProfileInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lua State List.
        /// </summary>
        internal static string LuaStateList {
            get {
                return ResourceManager.GetString("LuaStateList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lua-statelist.xml.
        /// </summary>
        internal static string LuaStatesFileName {
            get {
                return ResourceManager.GetString("LuaStatesFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lua Upvalues.
        /// </summary>
        internal static string LuaUpvalues {
            get {
                return ResourceManager.GetString("LuaUpvalues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lua Variable Parser.
        /// </summary>
        internal static string LuaVariableParser {
            get {
                return ResourceManager.GetString("LuaVariableParser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LuaVariableParserSettings.
        /// </summary>
        internal static string LuaVariableParserSettings {
            get {
                return ResourceManager.GetString("LuaVariableParserSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lua Variable Parser Settings.
        /// </summary>
        internal static string LuaVariableParserSettingsTitle {
            get {
                return ResourceManager.GetString("LuaVariableParserSettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lua Watch List.
        /// </summary>
        internal static string LuaWatchList {
            get {
                return ResourceManager.GetString("LuaWatchList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lua-memorytrace.xml.
        /// </summary>
        internal static string MemoryTraceFileName {
            get {
                return ResourceManager.GetString("MemoryTraceFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lua-memorytrace_stream.xml.
        /// </summary>
        internal static string MemoryTraceStreamFileName {
            get {
                return ResourceManager.GetString("MemoryTraceStreamFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /.
        /// </summary>
        internal static string MenuSeparator {
            get {
                return ResourceManager.GetString("MenuSeparator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        internal static string One {
            get {
                return ResourceManager.GetString("One", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.0.
        /// </summary>
        internal static string OnePointZero {
            get {
                return ResourceManager.GetString("OnePointZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ..
        /// </summary>
        internal static string Period {
            get {
                return ResourceManager.GetString("Period", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SLED Lua Language Plugin.
        /// </summary>
        internal static string PluginName {
            get {
                return ResourceManager.GetString("PluginName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .png.
        /// </summary>
        internal static string PngExtension {
            get {
                return ResourceManager.GetString("PngExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lua-profilefunccalls.xml.
        /// </summary>
        internal static string ProfileFuncCallsFileName {
            get {
                return ResourceManager.GetString("ProfileFuncCallsFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lua-profileinfo.xml.
        /// </summary>
        internal static string ProfileInfoFileName {
            get {
                return ResourceManager.GetString("ProfileInfoFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to }.
        /// </summary>
        internal static string RightSquigglyBracket {
            get {
                return ResourceManager.GetString("RightSquigglyBracket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  .
        /// </summary>
        internal static string Space {
            get {
                return ResourceManager.GetString("Space", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to True.
        /// </summary>
        internal static string True {
            get {
                return ResourceManager.GetString("True", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to U.
        /// </summary>
        internal static string U {
            get {
                return ResourceManager.GetString("U", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to u.
        /// </summary>
        internal static string ULower {
            get {
                return ResourceManager.GetString("ULower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Unknown&gt;.
        /// </summary>
        internal static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upvalue.
        /// </summary>
        internal static string Upvalue {
            get {
                return ResourceManager.GetString("Upvalue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upvalues.
        /// </summary>
        internal static string Upvalues {
            get {
                return ResourceManager.GetString("Upvalues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to upvalues.
        /// </summary>
        internal static string UpvaluesLower {
            get {
                return ResourceManager.GetString("UpvaluesLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to utf-8.
        /// </summary>
        internal static string UtfDashEight {
            get {
                return ResourceManager.GetString("UtfDashEight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verbose.
        /// </summary>
        internal static string Verbose {
            get {
                return ResourceManager.GetString("Verbose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Watches.
        /// </summary>
        internal static string Watches {
            get {
                return ResourceManager.GetString("Watches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lua-watchlist.xml.
        /// </summary>
        internal static string WatchListFileName {
            get {
                return ResourceManager.GetString("WatchListFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wait, what editor is this?.
        /// </summary>
        internal static string WhatEditorIsThis {
            get {
                return ResourceManager.GetString("WhatEditorIsThis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .xml.
        /// </summary>
        internal static string XmlExtension {
            get {
                return ResourceManager.GetString("XmlExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yes.
        /// </summary>
        internal static string YesLower {
            get {
                return ResourceManager.GetString("YesLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.
        /// </summary>
        internal static string Zero {
            get {
                return ResourceManager.GetString("Zero", resourceCulture);
            }
        }
    }
}
